### ISSUE TITLE
Assertion failed on macOS

### ISSUE THREAD

**Issue by jsaubry** [ImageMagick/ImageMagick6#1]
I've updated ImageMagick6 to version `6.9.9-42` with homebrew. I'm using it with the [ruby gem rmagick](https://github.com/rmagick/rmagick). 

ImageMagick crashes the ruby process with

```
Assertion failed: (image != (Image *) NULL), function NegateImageChannel, file magick/enhance.c, line 3991.
Received signal 6
```

I do not have the exact call causing the issue since it's breaking in a large code base. If it's required I could try to do a small script to reproduce the issue.

Downgrading to `6.9.9-40` fixes the issue.

**Comment by urban-warrior** [comment]
Does it still crash with the latest ImageMagick release 6.9.9-49?  If so, we'll investigate further.
