### ISSUE TITLE
Compare fails to find changes - ImageMagick7 works

### ISSUE THREAD

**Issue by Ian2020** [ImageMagick/ImageMagick6#100]
Under Fedora 32 and ImageMagick 6.9.11-27 `compare` tells me these two images have no differences:

Transparent PNG:

![blank](https://user-images.githubusercontent.com/7791246/94263635-3cfc4b80-ff2d-11ea-8c61-a5637c49801e.png)

Not so transparent PNG:

![blank_changed](https://user-images.githubusercontent.com/7791246/94263640-3ec60f00-ff2d-11ea-9d67-1215b08daada.png)

I run the following compare:

```
compare -metric AE blank.png blank_changed.png  /dev/null
```

...and am told there's no difference:

```
0
```
Under IM 7.0.10-30 I get a better answer:

```
832
```

I am currently trying to update to latest IM6 to test again.

**Comment by Ian2020** [comment]
Just confirmed this issue is still present under latest 6.9.11-30.

**Comment by Ian2020** [comment]
Found this: [Compare, including alpha channel](https://archive.imagemagick.org/discourse-server/viewtopic.php?t=22622) 

> ...most of the compare metrics do not do this 'transparency handling' and just compare values directly, which is why comparing images with transparency has such problems...

Perhaps compare just does not work with alpha then in IM6?

**Comment by urban-warrior** [comment]
Try this command:

```
compare -channel rgba -metric AE blank.png blank_changed.png  /dev/null
```

**Comment by Ian2020** [comment]
That's the answer, thanks for your help.
