### ISSUE TITLE
vertical stripes on images - IM 6.9.9-51 works fine

### ISSUE THREAD

**Issue by AbedAlkedda** [ImageMagick/ImageMagick6#103]
We are facing a strange problem recently with IM version 6.9.10-* and above.
Without a single convert command and just by reading and writing the same image multiple times, the original stripes on the image get stronger and more obvious which leads to distort the image.

source image
![soruce_image](https://user-images.githubusercontent.com/52959424/94421218-88a93200-0185-11eb-9ed2-11db4e590a56.jpg)

result
![result_image](https://user-images.githubusercontent.com/52959424/94421277-9f4f8900-0185-11eb-9957-647d0530e8ec.jpg)

First we thought that the problem has something to do with jpeg library that IM uses but we have tried different libraries (libjpeg-turbo 2.0.3, libjpeg-turbo 1.5, libjpeg62, libjpeg8, libjpeg9) and the bug appeared only on new versions of IM

We also tried to install old version of libjpeg on new version of IM but the Problem appeared as well that's why we think that it's a IM problem

The problem appeared on Ubuntu and Debian

Could someone kindly try to reproduce the problem?

**Comment by dlemstra** [comment]
Reproducing something without know the commands that were executed is not easy. Can you explain what you did in more detail?

**Comment by AbedAlkedda** [comment]
> Reproducing something without know the commands that were executed is not easy. Can you explain what you did in more detail?

The bug appeared first with this command
`for i in {0..8}; do j=$((i + 1)); convert test_image_${i}.jpg -resize 1024 -quality 90 test_image_${j}.jpg; done`

but even without `-resize` and `-quality` we reproduced it with something like
`for i in {0..8}; do j=$((i + 1)); convert test_image_${i}.jpg test_image_${j}.jpg; done`

**Comment by AbedAlkedda** [comment]
We use various convert commands and therefor we've tried it with simple command
Here is the test image we use

![test_image](https://user-images.githubusercontent.com/52959424/94425686-a037e900-018c-11eb-8158-d965e1400f32.jpg)

**Comment by urban-warrior** [comment]
JPEG is a lossy format.  Some differences are expected due to quantization.  We converted your image and the compare metric returned `75.9352 (0.0011587)` as the RMSE distortion.  You can try your conversion in a lossless format such as PNG or if you must remain with JPEG, understand the lossy compression format to better understand the pixel changes you are observing.

**Comment by AbedAlkedda** [comment]
I do understand the differences between different image file extensions. We use varied extensions in our application and some costumers reported this problem with JPEG extension.
As I mentioned above we reproduced the problem with this command:
`for i in {0..8}; do j=$((i + 1)); convert test_image_${i}.jpg test_image_${j}.jpg; done`

We did not convert the source image and did not do any magic on the image, just open the image and save it with different name using IM, in other words we just copied and pasted an image with stripes in it multiple times using IM.

The problem appeared using IM-6.9.10-23 and newer versions of IM but when we used the older version of IM (IM-6.9.9-51) the stripes did not appear. My question is, what do lossy compression format have to do with different versions of IM and why couldn't the problem appear using older version of IM although we are using the same image file extension JPEG?

Thanks in advance

**Comment by urban-warrior** [comment]
@fmw42 can you review this issue?  We're getting a normalized distortion of 0.001 which could readily be accounted for due to lossy compression.  If we use a format such as PNG, the distortion is 0 as expected.

**Comment by fmw42** [comment]
My tests show very small distortions for both, though the current version is somewhat larger.

```
IM 6.9.11.31
cd
cd desktop/test1
for ((i=0; i<8; i++)); do
j=$((i + 1))
convert test_image_${i}.jpg test_image_${j}.jpg
done
compare -metric rmse test_image_0.jpg test_image_8.jpg null:
176.662 (0.00269568)

approx 0.3%

```


```
IM 6.9.9.51
cd
cd desktop/test1
for ((i=0; i<8; i++)); do
j=$((i + 1))
im69951 convert test_image_${i}.jpg test_image_${j}.jpg
done
im69951 compare -metric rmse test_image_0.jpg test_image_8.jpg null:
21.5036 (0.000328124)

approx. 0.03%

```

This where the residuals show changes from versions:

**6.9.9.51 - 6.9.10.14 it was 21.5036 (0.000328124)
6.9.10.15 - 6.9.10.32 it was 417.47 (0.00637019) (much higher than currently)
6.9.10.33 - 6.9.11.31 it was 176.662 (0.00269568)**


The cause of the residuals is most likely compressing (writing) and uncompressing (reading) lossy JPG

I have no idea why there are changes in residuals over time. Perhaps changes in precision over time from slight changes in code corrections from fuzzing and such.

**Comment by AbedAlkedda** [comment]
As a temporary solution we downgraded IM to version 6.9.9-51 because this strange residuals also occurred using IM 7.

**Comment by philister** [comment]
In case you missed it: Even github seems to suffer from this  IM-Bug, as Abed's "source image" is shown with stripes (vertical, btw)
![screen-stripes](https://user-images.githubusercontent.com/118358/95061274-a897a300-06fb-11eb-9152-8dcc07f41656.png)

Here is the very original: https://assets.pictrs.com/static/verlauf.jpg

**Comment by fmw42** [comment]
Stripes may appear when you create a gradient that has more or less graylevels that 256. The best gradients would be one value each from 0 to 255. If you create a larger gradient then you get repetition of gray levels or interpolation between gray levels from resampling that get quantized to 256 values. Your gradient is also a JPG file which suffers from lossy compression.

**Comment by urban-warrior** [comment]
We're still investigating the differential between versions.  It could be caused by the JPEG compression defaults.  We'll need a week or two to track.  Stand by.

**Comment by urban-warrior** [comment]
Try adding `-define jpeg:dct-method=islow` to your command-line.  The RMSE was reduced to 0.000291293.

**Comment by fmw42** [comment]
On my Mac it went 

from 176.662 (0.00269568)
to 22.6673 (0.000345881)

**Comment by AbedAlkedda** [comment]
Is there any new updates on this one?

**Comment by fmw42** [comment]
From the comments above, it looks like it was resolved in IM 7.0.10.34.

**Comment by AbedAlkedda** [comment]
Is it possible to reduce the RMSE without adding `-define jpeg:dct-method=islow` ?

**Comment by urban-warrior** [comment]
ImageMagick uses the default JPEG delegate library.  The delegate library offers other methods: default, fastest, float, ifast, and islow.  Each method has its advantages and disadvantages.  If you want the advantages of a specific method, you must specify that method with the jpeg:dct define otherwise we use the default method.
