### ISSUE TITLE
[6.9.11]  CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1701

### ISSUE THREAD

**Issue by thinrope** [ImageMagick/ImageMagick6#110]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

A warning is displayed processing some images. I put one example on http://thinrope.net/tmp/K20_6051.JPG
This seems to be something new, I don't remember seeing it with previous versions few months ago, 6.9.11-31 is also affected.

### Steps to Reproduce
```
$ identify -version; identify /tmp/K20_6051.JPG 
Version: ImageMagick 6.9.11-34 Q16 x86_64 2020-10-23 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo fftw fontconfig freetype gslib gvc heic jng jp2 jpeg ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x zlib
/tmp/K20_6051.JPG JPEG 7360x4912 7360x4912+0+0 8-bit sRGB 10.1333MiB 0.000u 0:00.007
identify: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1701.
```

### System Configuration
- ImageMagick version: 6.9.11-34
- Environment (Operating system, version and so on): Gentoo
- Additional information: related to https://github.com/ImageMagick/ImageMagick/issues/1419 (but on 6.x)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by aravinthchellathurai** [comment]
Looks like this change is reverted in the below commit:

https://github.com/ImageMagick/ImageMagick6/commit/aba0e2a27a495de5f8454000f247dcedededed71

Now, I see DelegateLibrarySupportNotBuiltIn exception.
