### ISSUE TITLE
[6.9.11-44] Reading SGI image causes all RAM to by used and never finishes (DoS?)

### ISSUE THREAD

**Issue by keukentrap** [ImageMagick/ImageMagick6#114]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Reading these SGI images never finishes and keeps allocating memory from the heap until the complete RAM is filled.
The result is that all RAM and a full single core of a system are used when trying to read these specific images.
I have included several files that all produce this bug.

I noticed that Imagemagick 7 does not have this bug, but I haven't found an issue related to this bug.

I tried to debug it myself and came to the conclusion the bug is around reading the SGI image (ReadSGIImage)

### Steps to Reproduce
```
convert 1.sgi /dev/null
```
And this will use a full CPU core and as much RAM as possible until it is killed.

### System Configuration

- ImageMagick version: 6.9.11-44
- Environment (Operating system, version and so on): Debian 10, Ubuntu 20 LTS, Fedora 31
- Additional information:
Files can be found here: (UPDATED) https://drive.google.com/drive/folders/16ySuBcdvz3jSLamvdhKNPV7m-xEG_gMG?usp=sharing

This is my first bug report ever. So do not hesitate to ask for more info.

Okay since Github does not allow .sgi files, I just renamed the filename to .png:
(These aren't working images, this is just to attach them to the issue)
![1](https://user-images.githubusercontent.com/5173988/100633385-52776280-332e-11eb-92f7-ebf73179b1b4.png)
![2](https://user-images.githubusercontent.com/5173988/100633657-a5511a00-332e-11eb-94ec-d0e5d976215f.png)
![3](https://user-images.githubusercontent.com/5173988/100633673-a8e4a100-332e-11eb-8147-4159cc8740f3.png)
![4](https://user-images.githubusercontent.com/5173988/100633703-b00baf00-332e-11eb-9194-27ea11e832ad.png)
![5](https://user-images.githubusercontent.com/5173988/100633679-aaae6480-332e-11eb-9498-042ce18e1f96.png)
![6](https://user-images.githubusercontent.com/5173988/100633686-ac782800-332e-11eb-8791-fb05e360b5b4.png)
![7](https://user-images.githubusercontent.com/5173988/100633924-f103c380-332e-11eb-8143-e88dc0560fc5.png)
![8](https://user-images.githubusercontent.com/5173988/100633955-fa8d2b80-332e-11eb-9b51-8cf02ddb3913.png)
![9](https://user-images.githubusercontent.com/5173988/100633966-fd881c00-332e-11eb-8db2-a186c2370806.png)
![10](https://user-images.githubusercontent.com/5173988/100633971-ff51df80-332e-11eb-8a7f-03d95d437ef9.png)

**Comment by dlemstra** [comment]
Can you attach the 1.sgi file to the issue instead? I cannot find the file in the folder that was shared.

And feel free to open a discussion here https://github.com/ImageMagick/ImageMagick6/discussions or here https://github.com/ImageMagick/ImageMagick7/discussions with a link to your report when it is complete (of is het al klaar?) to share this knowledge.

**Comment by keukentrap** [comment]
Okay now you should be able to download the files. The report will be done tomorrow. If my group agrees I'll link the report in the discussion page (small summary: we found this bug when fuzzing webp images)

**Comment by dlemstra** [comment]
Thanks for fixing the links. What I always do when GitHub does not allow a specific format is to include the file (or files) in a zip file and attach that instead.

**Comment by dlemstra** [comment]
Thanks for reporting this appearently we forgot to set a variable in ImageMagick 6. This issue will be resolved in the next release.
