### ISSUE TITLE
Sun Rasterfile format appears unsupported from version 6.9

### ISSUE THREAD

**Issue by idlinds** [ImageMagick/ImageMagick6#117]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Attempting to convert Sun Rasterfile image (.SUN or .RAS) works under v6.7 but fails under version 6.9.

### Steps to Reproduce
Using [sample image from FileFormat.Info](https://www.fileformat.info/format/sunraster/egff.htm), MARBLES.SUN, attempt conversion to jpg.

Works under version 6.7:

$ convert --version
Version: ImageMagick 6.7.2-7 2016-06-17 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP    

$ identify MARBLES.RAS
MARBLES.RAS SUN 1419x1001 1419x1001+0+0 16-bit DirectClass 4.262MB 0.000u 0:00.000
$ convert MARBLES.RAS marbles.jpg
$

Fails under version 6.9:

$ convert --version
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
$ identify MARBLES.RAS
MARBLES.RAS SUN 1419x1001 1419x1001+0+0 16-bit sRGB 4262290B 0.000u 0:00.010
$ convert MARBLES.RAS marbles.jpg
convert-im6.q16: ImproperImageHeader `MARBLES.RAS' @ error/sun.c/ReadSUNImage/501.
convert-im6.q16: no images defined `marbles.jpg' @ error/convert.c/ConvertImageCommand/3258.
$

### System Configuration

- ImageMagick version: 6.7 and 6.9
- Environment (Operating system, version and so on): Version 6.7: Scientific Linux 6, version 6.9: Scientific Linux 7 / LMDE 4
- Additional information: Test image opens successfully in GIMP (Linux), Irfanview (Windows)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by rhysaph** [comment]
I'm also using .ras files. Thanks for the bugfix, identify now works:
 /usr/local/bin/identify rpgorbit_RandDiff_raster_example.ras  rpgorbit_RandDiff_raster_example.ras RAS 800x800 800x800+0+0 8-bit sRGB 256c 72338B 0.000u 0:00.000

Would it be possible to fix display and convert too please?

 /usr/local/bin/convert rpgorbit_RandDiff_raster_example.ras tst.jpg
convert: insufficient image data in file `rpgorbit_RandDiff_raster_example.ras' @ error/sun.c/ReadSUNImage/439.
convert: no images defined `tst.jpg' @ error/convert.c/ConvertImageCommand/3301.

 /usr/local/bin/display rpgorbit_RandDiff_raster_example.ras
display: insufficient image data in file `rpgorbit_RandDiff_raster_example.ras' @ error/sun.c/ReadSUNImage/439.

I'm using the latest version of the ImageMagick code via git clone.

/usr/local/bin/display --version
Version: ImageMagick 7.0.10-49 Q16 x86_64 2020-12-11 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(3.1) 
Delegates (built-in): bzlib x

**Comment by urban-warrior** [comment]
Check to see if convert and display share the same library revision as identify.  All utilities share the same version of the SUN image reader.  We tried 7.0.10-49 and we could display and convert the image without complaint.

**Comment by rhysaph** [comment]
Hi, thanks for the prompt response. I have built the latest ImageMagick using git clone on a freshly installed Scientific Linux 7 VM. and I still get the same issue. I have checked with ldd and --version, and it looks like it is the same library being used, but identify works, while convert and display don't.  I'm using the default ancient gcc (4.8.5) but make check shows 49/49 checks passed and I don't have the ImageMagick rpm package installed.

 identify ss.00000645.ras 
ss.00000645.ras RAS 800x800 800x800+0+0 8-bit sRGB 256c 39421B 0.000u 0:00.000

[rhys@localhost ~]$ display ss.00000645.ras 
display: insufficient image data in file `ss.00000645.ras' @ error/sun.c/ReadSUNImage/439.

[rhys@localhost ~]$ convert ss.00000645.ras test.jpg
convert: insufficient image data in file `ss.00000645.ras' @ error/sun.c/ReadSUNImage/439.
convert: no images defined `test.jpg' @ error/convert.c/ConvertImageCommand/3301.


 ldd /usr/local/bin/identify 
 linux-vdso.so.1 =>  (0x00007ffd1e130000)
 libMagickCore-7.Q16HDRI.so.8 => /usr/local/lib/libMagickCore-7.Q16HDRI.so.8 (0x00007feb42666000)
 libMagickWand-7.Q16HDRI.so.8 => /usr/local/lib/libMagickWand-7.Q16HDRI.so.8 (0x00007feb4232b000)
 libpthread.so.0 => /lib64/libpthread.so.0 (0x00007feb4210f000)
 libX11.so.6 => /lib64/libX11.so.6 (0x00007feb41dd1000)
 libgomp.so.1 => /lib64/libgomp.so.1 (0x00007feb41bab000)
 libm.so.6 => /lib64/libm.so.6 (0x00007feb418a9000)
 libc.so.6 => /lib64/libc.so.6 (0x00007feb414db000)
 libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007feb412c5000)
 /lib64/ld-linux-x86-64.so.2 (0x00007feb42c8b000)
 libxcb.so.1 => /lib64/libxcb.so.1 (0x00007feb4109d000)
 libdl.so.2 => /lib64/libdl.so.2 (0x00007feb40e99000)
 libXau.so.6 => /lib64/libXau.so.6 (0x00007feb40c95000)

ldd /usr/local/bin/convert
linux-vdso.so.1 =>  (0x00007ffc39f2c000)
libMagickCore-7.Q16HDRI.so.8 => /usr/local/lib/libMagickCore-7.Q16HDRI.so.8 (0x00007f0bb2993000)
libMagickWand-7.Q16HDRI.so.8 => /usr/local/lib/libMagickWand-7.Q16HDRI.so.8 (0x00007f0bb2658000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0bb243c000)
libX11.so.6 => /lib64/libX11.so.6 (0x00007f0bb20fe000)
libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f0bb1ed8000)
libm.so.6 => /lib64/libm.so.6 (0x00007f0bb1bd6000)
libc.so.6 => /lib64/libc.so.6 (0x00007f0bb1808000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f0bb15f2000)
/lib64/ld-linux-x86-64.so.2 (0x00007f0bb2fb8000)
libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f0bb13ca000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f0bb11c6000)
libXau.so.6 => /lib64/libXau.so.6 (0x00007f0bb0fc2000)

identify --version
Version: ImageMagick 7.0.10-49 Q16 x86_64 2020-12-14 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(3.1) 
Delegates (built-in): x 

convert --version
Version: ImageMagick 7.0.10-49 Q16 x86_64 2020-12-14 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(3.1) 
Delegates (built-in): x

**Comment by urban-warrior** [comment]
It may be an issue specific to your ss.00000645.ras image.  Can you post a link to the image so we can download it and reproduce the issue.

**Comment by rhysaph** [comment]
Certainly, here it is:
https://www.dropbox.com/s/vbbvl4t9v0x3znh/ss.00000645.ras?dl=0
it did open fine in ImageMagick 6.7. 
It did produce a warning/error but did display the file.
display ss.00000645.ras
display: unexpected end-of-file `ss.00000645.ras': No such file or directory @ error/sun.c/ReadSUNImage/568.
(It did display the image!)

junk[mensa]rahm: display --version
Version: ImageMagick 6.7.2-7 2017-03-22 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP

**Comment by rhysaph** [comment]
I think you're right about the file, I tried the marbles.sun file mentioned above and that works fine in the newest display and convert without a error/warning, so there may be slightly different kinds of .ras files - which is a pain.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by rhysaph** [comment]
That's amazing, thank you.
I'll test it and get back to you as soon as I can.

**Comment by urban-warrior** [comment]
ImageMagick in the last couple of years has added additional sanity checks to prevent reading of nefarious images.  Your ss.00000645.ras is actually corrupt.  The internal length parameter is incorrect and we get an end of file when reading it.  This is confirmed by two other utilities that return exceptions when reading the image, although Gimp reads the image without complaint.  We no longer have access to a Sun system.  Can the image be viewed on a Sun system?  If we loosen the sanity checks to read this image, we may be introducing a vector for security issues.  If the image is truly corrupt, ImageMagick should reject it.  How confident are you that ss.00000645.ras is sane and follows the RAS standard?

**Comment by rhysaph** [comment]
OK, I think I will have to have a look at the code that generates these images to answer that question.
Thanks for all your help so far.

**Comment by urban-warrior** [comment]
I think the issue is that the image is runlength-encoded.  We tested with five different utilities and half of them could read it and half could not.  We did read that the length field is not considered reliable.  We can patch to accept this file.  Look for an update, likely by tomorrow.

**Comment by rhysaph** [comment]
display and convert work perfectly now, even on the dodgy file, thank you for being so helpful and so quick!
We will look at the software that is generating bad versions of an outdated file type with a view to getting it to use another output format. But for now, we have a solution that works on both SL/Centos6 and SL/Centos7 which is fantastic.
Thanks again.
