### ISSUE TITLE
"-annotate XdegreesxYdegrees {+-}tx{+-}ty text" documented but never implemented

### ISSUE THREAD

**Issue by jidanni** [ImageMagick/ImageMagick6#128]
file:///usr/share/doc/imagemagick-6-common/html/www/command-line-options.html#annotate
says
```
-annotate XdegreesxYdegrees {+-}tx{+-}ty text
```
Alas,
```
$ convert ../JPGS/51-m0368-068.jpg -annotate 25x25 +4725+3300 XXXXXXXXXXX -crop 1221x560+4269+2977 -rotate 25 xx.jpg
convert-im6.q16: unable to open image `XXXXXXXXXXX': No such file or directory @ error/blob.c/OpenBlob/2924.
convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/566.
```

**Comment by urban-warrior** [comment]
Remove the space after the angle, i.e. `25x25+4725+3300`.  Does that return expected results?

**Comment by jidanni** [comment]
Apparently this is already fixed in https://imagemagick.org/script/command-line-options.php#annotate

**Comment by jidanni** [comment]
(Perhaps the program could make a better error message in this situation. Like some "Usage: " message mentioning annotation.)

**Comment by urban-warrior** [comment]
No easy way to determine the user intent.  Annotate takes two arguments.  If there is a third, its assumed its a filename unless it starts with +/-, then its an option.
