### ISSUE TITLE
Debian side regression

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick6#130]
Just send you a mail but it seems that we have a regression on the debian side between .46 and .57

See https://tracker.debian.org/pkg/imagemagick

Ignore ruby-magick that is already broken.

Do you have an idea?

**Comment by urban-warrior** [comment]
gscan2pdf had a network issue, presumably unrelated to ImageMagick.  imagick has one issue with the 50% interval returning 32767 when it should return 32828.  See https://github.com/ImageMagick/ImageMagick6/commit/f38ca0d37cae50de4b44ddedbd89acd4259f8903.  Please verify.  We will release 6.9.11-58 today that includes the patch.

If you have additional problems, let us know and we'll fix within a day or two.

**Comment by bastien-roucaries** [comment]
Hi,

Cristy could you geta glimpse at
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980202

It seems this is our breakage

Bastien

**Comment by urban-warrior** [comment]
Working on it.  Give us a few days and we will post here when we make some progress.

**Comment by urban-warrior** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980202 claims 
```
convert +matte -depth 1 -colorspace Gray -pointsize 12 -units PixelsPerInch -density 300 label:"The quick brown fox" test.png
```
returns unexpected results.  We tried the command with ImageMagick 6.9.11-58 and get expected results under Fedora 33 and Debian 4.19.160-2 I686.  Can you try -58 on our system.  Do you get expected results (test-old.png from bug report)?  If not, tell us how to reproduce the problem.

**Comment by bastien-roucaries** [comment]
I have uploaded 8.9.11.58 under debian unstable.

THis have fixed the i386 regression on php but not the gscan2pdf problem....

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow. 

The problem was a performance optimization that broke text rendering.  We reverted the patch.  The official -58 release will be available within a few days.

**Comment by bastien-roucaries** [comment]
Hi,

Unofrtunatly it seems not fixed on the gscan2pdf side

Bastien
