### ISSUE TITLE
[6.9.11-61] Please bump version for new soname

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick6#133]
6.9.11-60 use soname 7
6.9.11-61 use soname 8

This is terrible as it makes impossible to install both versions, as the coder are in `ImageMagick-6.9.11`.

Please but version to at least **6.9.12**

**Comment by remicollet** [comment]
Please also bump `libMagick++` soname (from 8 to 9)

**Comment by urban-warrior** [comment]
We intend to release 6.9.11-62 this weekend. Next week, we will bump to 7.0.11-0 and 6.9.12-0 as you recommend.

**Comment by urban-warrior** [comment]
ImageMagick 6.9.12-0 is released.
