### ISSUE TITLE
Segfault at convert 

### ISSUE THREAD

**Issue by franktg** [ImageMagick/ImageMagick6#136]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

 6.9.10-23 Q16 x86_64 20190101 

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04 LTS up to date

### Description
PHP Crash: 

 [1110435.527476] php-fpm7.4[1378287]: segfault at 0 ip 00007f3902bfde25 sp 00007ffed101a1c0 error 4 in libMagickCore-6.Q16.so.6.0.0[7f3902ad6000+1cb000]

(gdb) bt
#0  0x00007f0325d6fe25 in ?? () from /lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6
ImageMagick/ImageMagick#1  0x00007f0325aa58e6 in GOMP_parallel () from /lib/x86_64-linux-gnu/libgomp.so.1
ImageMagick/ImageMagick#2  0x00007f0325d716a0 in ProfileImage () from /lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6
ImageMagick/ImageMagick#3  0x00007f0325f8a2af in MagickProfileImage () from /lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.6
ImageMagick/ImageMagick#4  0x00007f0326044778 in zim_imagick_profileimage () from /usr/lib/php/20190902/imagick.so
ImageMagick/ImageMagick#5  0x000055c80618f119 in execute_ex ()
ImageMagick/ImageMagick#6  0x000055c8061906db in zend_execute ()
ImageMagick/ImageMagick#7  0x000055c80610777c in zend_execute_scripts ()
ImageMagick/ImageMagick#8  0x000055c8060a7460 in php_execute_script ()
ImageMagick/ImageMagick#9  0x000055c805f712bb in ?? ()
ImageMagick/ImageMagick#10 0x00007f0328d390b3 in __libc_start_main (main=0x55c805f70380, argc=4, argv=0x7fff7667e848,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff7667e838)
    at ../csu/libc-start.c:308
ImageMagick/ImageMagick#11 0x000055c805f7211e in _start ()

Convert(1) crash:

$ convert --version
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

$ gdb --args convert testimage.jpg -profile sRGB_v4_ICC_preference.icc testimage.png

(gdb) run
Starting program: /usr/bin/convert testimage.jpg -profile sRGB_v4_ICC_preference.icc testimage.png
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe8efb700 (LWP 1857253)]
[New Thread 0x7fffe86fa700 (LWP 1857254)]
[New Thread 0x7fffe7ef9700 (LWP 1857255)]

Thread 4 "convert" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe7ef9700 (LWP 1857255)]
0x00007ffff7e51e25 in ?? () from /lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6
(gdb) bt
#0 0x00007ffff7e51e25 in ?? () from /lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6
ImageMagick/ImageMagick#1 0x00007ffff6fa277e in ?? () from /lib/x86_64-linux-gnu/libgomp.so.1
ImageMagick/ImageMagick#2 0x00007ffff6f53609 in start_thread (arg=) at pthread_create.c:477
ImageMagick/ImageMagick#3 0x00007ffff7afa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

### Steps to Reproduce

$  convert testimage.jpg -profile sRGB_v4_ICC_preference.icc testimage.png

[files.zip](https://github.com/ImageMagick/ImageMagick/files/6130122/files.zip)

**Comment by franktg** [comment]
> Can you reproduce this issue with the latest version of ImageMagick 6?

I will compile that from source.
Note that in 7.0.10-61 the problem is non-existent. 

Maybe this is more of a Ubuntu-version problem than Imagemagick?

**Comment by urban-warrior** [comment]
We tried your command with 6.9.12-3 on a CentOS 8 VM.  It ran without complaint.  Can you try this release on your Ubuntu host?  Does it still throw an exception?

**Comment by franktg** [comment]
Compiled from sources on Ubuntu 20.04 LTS with all updates installed. Looks fine.

frank@x:~/ig/bin$ ./convert --version
Version: ImageMagick 6.9.12-3 Q16 x86_64 2021-02-27 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC OpenMP(4.5)
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr lzma openexr pangocairo png tiff webp x xml zlib

frank@x:~/ig/bin$ ./convert /home/frank/files/testimage.jpg -profile /home/frank/files/sRGB_v4_ICC_preference.icc /home/frank/files/testimage.png

**Comment by franktg** [comment]
Anyone have any idea which commit fixed this?
