### ISSUE TITLE
GitLab mirror is not being updated

### ISSUE THREAD

**Issue by Lastique** [ImageMagick/ImageMagick6#147]
The GitLab mirror at https://gitlab.com/ImageMagick/ImageMagick6/ (which is mentioned in the README.md) has the latest tag 6.9.10-46 from 2019-05-18, and the latest commit is from 2019-05-27. It looks like that mirror is not being updated.

**Comment by urban-warrior** [comment]
We removed the Gitlab mirror from the ImageMagick mirror list.  The authoritative source of ImageMagick is on Github.
