### ISSUE TITLE
Latest release on GitHub page says 6.9.11-22

### ISSUE THREAD

**Issue by Lastique** [ImageMagick/ImageMagick6#148]
For some reason, GitHub [project page](https://github.com/ImageMagick/ImageMagick6) says the latest release is 6.9.11-22, while the currently latest is 6.9.12-8. Perhaps, release tags need to be augmented somehow to update the latest release link?

**Comment by urban-warrior** [comment]
The project page now reflects the proper latest release.

**Comment by Lastique** [comment]
The project page currently doesn't show the latest release at all, but there is a link to the list of tags, where one can select the latest one. At least, there's no misinformation on the project page. Works for me, thanks.
