### ISSUE TITLE
Imagemagick6 does not support reading metadata from webp images

### ISSUE THREAD

**Issue by romanb089** [ImageMagick/ImageMagick6#157]
### Prerequisites

- [*] I have written a descriptive issue title
- [*] I have verified that I am using the latest version of ImageMagick
- [*] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Imagemagick 7* supports webp image metadata, while Imagemagick 6 does not. 

### Steps to Reproduce
To install Imagemagick I use this command:

```bash
git clone https://github.com/ImageMagick/ImageMagick6.git \
    && cd ImageMagick6 \
    && ./configure --with-webp=yes \
    && make \
    && make install \
    && ldconfig /usr/local/lib \
    && identify -version
```
when running `./configure --with-webp = yes`, the presence of libraries for working with webp is displayed
```bash
    checking for libwebp >= 0.4.1... yes
    checking for libwebpmux >= 0.5.0 libwebpdemux >= 0.5.0... yes
```

To check the metadata output, I run the command
```bash
$ identify  -format '%[EXIF:*]'  johnrogershousemay2020.webp
// no result

$ identify -version
Version: ImageMagick 6.9.12-16 Q16 x86_64 2021-06-12 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC OpenMP(4.5) 
Delegates (built-in): fontconfig freetype jbig jng jpeg lzma png tiff webp x xml zlib

$ identify -list format | grep webp
     WEBP* rw+   WebP Image Format (libwebp 0.6.1 [020E])
```

Similarly, I create a new docker container and install ImageMagick 7*

```bash
git clone https://github.com/ImageMagick/ImageMagick.git \
    && cd ImageMagick \
    && ./configure --with-webp=yes \
    && make \
    && make install \
    && ldconfig /usr/local/lib \
    && identify -version
```

```bash
$ identify  -format '%[EXIF:*]'  johnrogershousemay2020.webp
exif:ColorSpace=65535
exif:ComponentsConfiguration=1, 2, 3, 0
exif:ExifOffset=98
exif:ExifVersion=48, 50, 51, 49
exif:FlashPixVersion=48, 49, 48, 48
exif:ResolutionUnit=2
exif:UserComment=65, 83, 67, 73, 73, 0, 0, 0, 123, 34, 102, 111, 111, 34, 58, 34, 98, 97, 114, 34, 125
exif:XResolution=72/1
exif:YCbCrPositioning=1
exif:YResolution=72/1

$ identify -version
Version: ImageMagick 7.1.0-0 Q16 x86_64 2021-06-13 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): fontconfig freetype jbig jng jpeg lzma png tiff webp x xml zlib

$ identify -list format | grep webp
     WEBP* rw+   WebP Image Format (libwebp 0.6.1 [020E])
```

For tests I used [this image](https://drive.google.com/file/d/1Ie7lTBvc1BhbsUiiBRdDXwnOVdIGmcf8/view)

### System Configuration

- ImageMagick version: 6.9.12-16
- Environment (Operating system, version and so on): Linux Mint 19.3 Tricia
- Additional information: Docker version: 20.10.7 (openresty/openresty:focal)

**Comment by dlemstra** [comment]
This is not a bug but a feature. We will not add new functionality to ImageMagick 6 and that is why this is not available there.

**Comment by romanb089** [comment]
It's a shame that imagemagick6 won't get this update, but thanks anyway for the answer
