### ISSUE TITLE
6.9.11-22 fails to build with visual studio 2013

### ISSUE THREAD

**Issue by WilliamBehrens** [ImageMagick/ImageMagick6#161]
### ImageMagick version

6.9.11-22

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

After pulling in all the repos and running the configure program for vs2013 and opening the solution, 1. It seems to want to use windows xp libraries, and, 2. I get a ton of syntax errors inside of files from CORE_aom, weirdly though opening these files in the editor doesnt show anything

### Steps to Reproduce

Follow image magick install tutorial for windows, build configure for vs2013 win32, attempt to build the project.

**Comment by dlemstra** [comment]
We just stopped supporting Visual Studio 2012 and 2013. You will need to use at least VS2015 or higher.
