### ISSUE TITLE
The first run will be stuck for about 5 seconds

### ISSUE THREAD

**Issue by ahwh123123** [ImageMagick/ImageMagick6#163]
### ImageMagick version

6.9.12-19

### Operating system

Windows

### Operating system, version and so on

windows 10 64-bit

### Description

Official website download: ImageMagick-6.9.12-19-Q16-**x86**-dll.exe
After installation, reduce the picture

Picture used in the test abc.jpg File size: 200kb

first:
convert -resize 128x128 abc.jpg abc-2.jpg
The whole process took about 5 seconds.

the second time:
convert -resize 128x128 abc.jpg abc-2.jpg
The whole process took about 0.1 second.

I changed to another computer, win 10 64 bit, installed ImageMagick-6.9.12-19-Q16-x86-dll.exe

first:
convert -resize 128x128 abc.jpg abc-2.jpg
The whole process still took about 5 seconds.

the second time:
convert -resize 128x128 abc.jpg abc-2.jpg
The whole process took about 0.1 second.

Then, download from the official website: ImageMagick-6.9.12-19-Q16-**x64**-dll.exe

Win 10 (64-bit) on the third new computer

first:
convert -resize 128x128 abc.jpg abc-2.jpg
The whole process took about 0.1 second.

the second time:
convert -resize 128x128 abc.jpg abc-2.jpg
The whole process took about 0.1 second.

Why ImageMagick-6.9.12-19-Q16-**x86**-dll.exe will be stuck for about 5 seconds when it runs for the first time on a win 10 64-bit machine. The second run will be much faster.

### Steps to Reproduce

Official website download: ImageMagick-6.9.12-19-Q16-**x86**-dll.exe
After installation, reduce the picture

Picture used in the test abc.jpg File size: 200kb

first:
convert -resize 128x128 abc.jpg abc-2.jpg
The whole process took about 5 seconds.

the second time:
convert -resize 128x128 abc.jpg abc-2.jpg
The whole process took about 0.1 second.

**Comment by dlemstra** [comment]
This is happening because an OpenCL benchmark is performed. But that should only happen when OpenCL is enabled. I just push a patch to fix this in the next release.
