### ISSUE TITLE
Sixel image files cannot be scaled, image turns black

### ISSUE THREAD

**Issue by hackerb9** [ImageMagick/ImageMagick6#167]
### ImageMagick version

6.9.10-14

### Operating system

Linux

### Operating system, version and so on

Ubuntu GNU/Linux 19.04

### Description

Images files in sixel format cannot be scaled. Doing so results in a completely black image. 

By the way, the images do load correctly and can be converted to other formats, it is only when scaling that the output is corrupted. This is broken for -geometry, -scale, -resample, -resize, -adaptive-resize, and -thumbnail. Perhaps it will help you to track down the bug to know that it does not occur for -sample. 

### Steps to Reproduce

```bash
convert  logo:  logo.sixel
convert  logo.sixel  -geometry 50%  logo.png
display  logo.png
```

### Images

![image](https://user-images.githubusercontent.com/10174223/132967385-259954c2-48fc-4fdc-bf35-0f34846b544d.png)

The above is the ImageMagick Wizard logo after being read as a sixel file by ImageMagick.

**Comment by dlemstra** [comment]
Thanks for reporting this. This issue will be resolved in the next release.
