### ISSUE TITLE
Compare images failing after commit 1219eac5d3bfb796753597f37412df567f629c08 

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick6#170]
### ImageMagick version

 6.9.12-30

### Operating system

Linux

### Operating system, version and so on

Debian 11

### Description

Calls to MagickCompareImages seem to always fail and return null from commit 1219eac5d3bfb796753597f37412df567f629c08 onwards.

The previous commit 7599dd92e8ad19993a2eb27a2b5103d853bce57f compareImages seems to work fine.

### Steps to Reproduce

This is PHP code. I can do a C version if you really need it.

```
<?php

$image = new Imagick();
$image->newPseudoImage(640, 480, "magick:logo");

$image2 = new Imagick();
$image2->newPseudoImage(640, 480, "magick:logo");

$result = $image->compareImages($image2, \Imagick::METRIC_MEANABSOLUTEERROR);

// Fatal error: Uncaught ImagickException: Compare images failed in /var/app/tests/bug59378.php:26

```

**Comment by urban-warrior** [comment]
Try the official 6.9.12-30 release as of yesterday.  Let us know if the issue is fixed.

**Comment by Danack** [comment]
Thanks yeah. Re-running the CI and it seems fixed.
