### ISSUE TITLE
Windows binaries broken since 6.9.12-41?

### ISSUE THREAD

**Issue by responseinformationsdesign** [ImageMagick/ImageMagick6#185]
### ImageMagick version

6.9.12-41/6.9.12-42/6.9.12-45/6.9.12-46/6.9.12-54

### Operating system

Windows

### Operating system, version and so on

Windows Server 2012 R2

### Description

- Logging settings in log.xml ignored
- PDFDelegateFailed (Looking for GhostScript as "gs" instead of windows versions (gswin64c, gswin32c) 

### Steps to Reproduce

Tested/Reproducible with versions 6.9.12-41/6.9.12-42/6.9.12-45/6.9.12-46/6.9.12-54 of convert.exe of windows binary release ImageMagick-6.9.12-XX-Q16-x64-static.exe.

No error under version 6.9.12-37 and below.
Can´t test 6.9.12-38 up to 6.9.12.40 as these binaries are not available any more.

**Comment by dlemstra** [comment]
Your issue does not contain enough information. What is the exact error message that you are getting? And which log settings are ignored and how did you test that?

**Comment by responseinformationsdesign** [comment]
Content of log.xml

<logmap>
  <log events="all"/>
  <log output="file"/>
  <log filename="C:\temp\Magick-%g.log"/>
  <log generations="3"/>
  <log limit="2000"/>
  <log format="%t %r %u %v %d %c[%p]: %m/%f/%l/%d\n  %e"/>
</logmap>

(no file written if version > 6.9.12-41)

Problem with delegation for pdf files:

convert.exe: FailedToExecuteCommand `"gs" [...] (Das System kann die angegebene Datei nicht finden.) @ error/delegate.c/ExternalDelegateCommand/495.
convert.exe: PDFDelegateFailed `Das System kann die angegebene Datei nicht finden. ' @ error/pdf.c/ReadPDFImage/701.
convert.exe: NoImagesDefined ` [...] ' @ error/convert.c/ConvertImageCommand/3229.

**Comment by dlemstra** [comment]
It looks like `convert.exe` is unable to find your config files. You seem to be using the internal build-in configuration.

**Comment by dlemstra** [comment]
It looks like this has to do with us now trying to read an `UTF8` path from the registry. We will need to investigate this and see how we can resolve this.

**Comment by dlemstra** [comment]
We just applied some patches and this should be resolved in the next release.

**Comment by responseinformationsdesign** [comment]
Indeed - issue is fixed in version 6.9.12-55.

Thanks!
