### ISSUE TITLE
"inner" trim not working in Imagemagick 6

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick6#187]
### ImageMagick version

6.9.12-54

### Operating system

MacOS

### Operating system, version and so on

Monterey on M1 Mac mini

### Description

"inner trim" using -define trim:percent-background=0% -trim works fine in Imagemagick 7 but not Imagemagick 6.

Input:

![preview_edited_inner6](https://user-images.githubusercontent.com/13458218/176272444-dda2563a-02df-4e22-bcbc-eec26aca1ae5.jpg)

Imagemagick 6.9.12-54

`convert preview_edited_inner6.jpg -background "gray(0)" -fuzz 5% -define trim:percent-background=0% -trim +repage x6.jpg`

![x6](https://user-images.githubusercontent.com/13458218/176272514-32cce65c-1a70-4bd9-b21e-86e13554e398.jpg)

Imagemagick 7.1.0-39

`magick preview_edited_inner6.jpg -background "gray(0)" -fuzz 5% -define trim:percent-background=0% -trim +repage x7.jpg`

![x7](https://user-images.githubusercontent.com/13458218/176272685-f078f144-cd6c-4c01-b5cf-b863ad637408.jpg)

### Steps to Reproduce

See above

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
