### ISSUE TITLE
TIFF output does not preserve input depth

### ISSUE THREAD

**Issue by luyatshimbalanga** [ImageMagick/ImageMagick6#188]
### ImageMagick version

6.9.12-52

### Operating system

Linux

### Operating system, version and so on

Fedora 36

### Description

The conversion from png to tiff failed to preserve the image depth.
The original report is from [Red Hat Bugzilla dating from 2016](https://bugzilla.redhat.com/show_bug.cgi?id=1378891).

### Steps to Reproduce

```
convert in.png out.tiff
 file in.png 
in.png: PNG image data, 157 x 196, 1-bit grayscale, non-interlaced
file out.tiff 
out.tiff: TIFF image data, little-endian, direntries=17, height=196, bps=8, compression=deflate, PhotometricIntepretation=BlackIsZero, orientation=upper-left, width=157
```

### Images

Referenced image
![in](https://user-images.githubusercontent.com/7230131/177057454-24cc538b-67ea-4f7d-b3bb-6f6a38f1058e.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by sergiomb2** [comment]
from https://bugzilla.redhat.com/show_bug.cgi?id=1378891#c44

This seems to be fixed everywhere now. Unless "file" tool lies. Tested with:

ImageMagick-7.1.0.62-1.fc39.x86_64
ImageMagick-7.1.0.57-4.fc38.x86_64
ImageMagick-6.9.12.77-1.fc37.x86_64
ImageMagick-6.9.12.77-1.fc36.x86_64
