### ISSUE TITLE
Different color result between ImageMagick 6.5.4-7 and ImageMagick 6.9.12-50

### ISSUE THREAD

**Issue by gzhcoder** [ImageMagick/ImageMagick6#190]
### ImageMagick version

6.9.12-50

### Operating system

Linux

### Operating system, version and so on

Red Hat Enterprise Linux release 8.5 (Ootpa)

### Description

I have had a PHP Website working for 7 years and have had no problems
until a few weeks ago I replaced my ImageMagick with a newer one.

ImageMagick (old): ImageMagick 6.5.4-7
OS (old): CentOS release 6.4 (Final)

ImageMagick (new): ImageMagick 6.9.12-50
OS (new): Red Hat Enterprise Linux release 8.5 (Ootpa)

I run following command in ImageMagick 6.5.4-7 and ImageMagick 6.9.12-50, it returns different color results.

[root@ImageMagickTest ~]# /usr/bin/convert -colorspace RGB "/home/share/from_file.jpeg" "/home/share/to_file.jpeg"

JPG（to_file.jpeg） file generated with ImageMagick 6.9.12-50 looks darker in color.
The JPG（to_file.jpeg） file of the new version is not as clear as the old version.
When I use the file_get_contents() to read the contents of to_file.jpg into a string.
The contents of the string are also different.

What is the reason for this and is there any easy way to maintain compatibility?
How to set the new version to get the same results as the old version?

### Steps to Reproduce

` /usr/bin/convert -colorspace RGB "/home/share/from_file.jpeg" "/home/share/to_file.jpeg"`

### Images

from_file.jpeg
![from_file](https://user-images.githubusercontent.com/23540382/177239014-08755e48-e888-4dce-868d-4b5846b35a09.jpeg)

to_file.jpeg
![to_file](https://user-images.githubusercontent.com/23540382/177239017-e1b87090-78f7-43d6-880a-e5830a54b24d.jpeg)

**Comment by dlemstra** [comment]
Please don't create an issue and a discussion about the same thing.

**Comment by gzhcoder** [comment]
> Please don't create an issue and a discussion about the same thing.

I'm sorry I have released the same problem, I don't know how to delete discussion. Can you close the discussion and retain this issue?
