### ISSUE TITLE
SVG not rendered correctly

### ISSUE THREAD

**Issue by olcc** [ImageMagick/ImageMagick6#193]
### ImageMagick version

6.9.11.60

### Operating system

Linux

### Operating system, version and so on

Debian testing

### Description

The conversion of this SVG image to PNG shows errors:
- The subscripts "1" and "2" are rendered too small.
- The character `R'` in the original text is transformed to `R\'`.
- The apostrophe in `R'` disappear in the chemical formula.
- A big bar is added over the chemical formula.

You can view the original SVG image correctly in a browser or in Inkscape.

### Steps to Reproduce

Just run: `convert HEUR.svg HEUR.png`

### Images

![HEUR](https://user-images.githubusercontent.com/5873395/180647731-1689e90e-960a-4013-ba60-73801fe72a69.svg)
![HEUR](https://user-images.githubusercontent.com/5873395/180647749-db7ee146-9c12-466b-b36c-09a433dd6d72.png)

**Comment by fmw42** [comment]
Imagemagick can use any of 3 SVG renderers:  its internal MSVG/XML renderer, RSVG delegate and Inkscape in order of better quality. Load Inkscape on your system and Imagemagick should be able to find it and use it. I have used it to render in Imagemagick and it looks fine to me.

![x](https://user-images.githubusercontent.com/13458218/180653743-4c00e173-c736-44c0-98b1-4f6c6ee9d388.png)

**Comment by olcc** [comment]
Thank you. 
(1) Should the IM MSVG renderer be improved with respect to this example?
(2) Can you indicate your comand line for using `inkscape` from `convert`?
- I do have Inkscape installed, but IM does not seem to use it.
- I do have `rsvg-convert` installed and the rendering is good, but `convert` does not use it.

```
$ convert -list format | grep -i svg
MSVG  SVG       rw+   ImageMagick's own SVG internal renderer
 SVG  SVG       rw+   Scalable Vector Graphics (XML 2.9.4)
SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.4)
```

**Comment by fmw42** [comment]
I just used

`convert image.svg image.png
`
and that works if Inkscape is installed and IM can find it.

What do you get from 

`convert -version`

Does it list RSVG?  If not, then IM was not installed with that delegate even if you have it on your system. You would need to re-install after installing the RSVG delegate.

IM should be able to find Inkscape if both are in your $PATH environment variable.

Be sure with either RSVG or Inkscape to install the latest versions.

MSVG will not likely be improved (other than bugs), since RSVG and Inkscape are available and better (in my opinion)

**Comment by olcc** [comment]
Everything looks accessible from my $PATH:
```
$ convert -version
Version: ImageMagick 6.9.10-2 Q16 x86_64 20180618 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib

$ inkscape --version
Inkscape 1.1.2 (0a00cf5339, 2022-02-04)

$ rsvg-convert --version
rsvg-convert version 2.54.4
```

**Comment by fmw42** [comment]
Be sure that Inkscape is in your $PATH as Imagemagick. RSVG may not be available because it was not installed with compilation of Imagemagick.  If all else fails, upgrade to the current Imagemagick.

**Comment by olcc** [comment]
> Be sure that Inkscape is in your $PATH

What does that mean exactly? I can run `inkscape` from the command line because `/usr/bin` is in my `$PATH` and the binary is `/usr/bin/inkscape`. Is there something more needed?

**Comment by fmw42** [comment]
Is both Imagemagick and Inkscape in your $PATH environment variable. If so, the perhaps upgrade Inkscape and/or Imagemagick.

**Comment by kleisauke** [comment]
> ImageMagick utilizes [inkscape](http://www.inkscape.org/) if its in your execution path otherwise [RSVG](http://developer.gnome.org/rsvg/). If neither are available, ImageMagick reverts to its internal SVG renderer.

It looks like commit https://github.com/ImageMagick/ImageMagick6/commit/58ad45805c9c59eb80b85716eb0ba02f14b43c29 (released in version 6.9.12-59) makes the internal MSVG/XML renderer always no-op, so this comment is no longer correct. 

AFAIK, the only way to utilize the internal MSVG/XML renderer is to remove the `svg:decode` delegate in `delegates.xml`. On Windows, you may also need to set the `MAGICK_CONFIGURE_PATH` environment variable.

**Comment by sergiomb2** [comment]
Hello , I also have a report about svg covert problem [1] seems related but I not sure , it suggest that version of SVG have impact over convert of ImageMagick

[1]
https://bugzilla.redhat.com/show_bug.cgi?id=2140018

**Comment by dlemstra** [comment]
Using `MSVG:` can be used to force the MSVG coder.

**Comment by olcc** [comment]
I confirm that with my current version, the convertion `convert HEUR.svg HEUR.png` produces a good image.
```
$ convert -version
Version: ImageMagick 6.9.12-98 Q16 x86_64 18038 https://legacy.imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png raw tiff webp wmf x xml zlib
```
