### ISSUE TITLE
Suspected memory disclosure

### ISSUE THREAD

**Issue by agoodm88** [ImageMagick/ImageMagick6#197]
### ImageMagick version

6 (head)

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

I've been throwing resources at fuzzing imagemagick6 convert again.  I've found a bunch of undefined behaviour issues that I am still triaging.

The one I am reporting today caught my attention because it causes convert to output a PAM image with a corrupted header.  The behaviour is very non deterministic yet it did not trigger MSAN or ASAN/UBSAN/etc.

Valgrind suggests there is uninitialised memory in the output and the output is inconsistent between runs (I am specifically triaging for inputs that cause inconsistent outputs)

Valgrind output:
$ valgrind convert ../corruptedoutputheader PAM:-
==166847== Memcheck, a memory error detector
==166847== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==166847== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==166847== Command: convert ../corruptedoutputheader PAM:-
==166847== 
==166847== Syscall param write(buf) points to uninitialised byte(s)
==166847==    at 0x4D80A37: write (write.c:26)
==166847==    by 0x4CF6F6C: _IO_file_write@@GLIBC_2.2.5 (fileops.c:1180)
==166847==    by 0x4CF8A60: new_do_write (fileops.c:448)
==166847==    by 0x4CF8A60: _IO_new_do_write (fileops.c:425)
==166847==    by 0x4CF8A60: _IO_do_write@@GLIBC_2.2.5 (fileops.c:422)
==166847==    by 0x4CF6557: _IO_file_sync@@GLIBC_2.2.5 (fileops.c:798)
==166847==    by 0x4CEB229: fflush (iofflush.c:40)
==166847==    by 0x48B4BF7: CloseBlob (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==166847==    by 0x4866089: ??? (in /usr/lib/x86_64-linux-gnu/ImageMagick-6.9.11/modules-Q16/coders/pnm.so)
==166847==    by 0x48ECEEC: WriteImage (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==166847==    by 0x48ED905: WriteImages (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==166847==    by 0x4B7D9BC: ConvertImageCommand (in /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.6.0.0)
==166847==    by 0x4BE8C1E: MagickCommandGenesis (in /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.6.0.0)
==166847==    by 0x10917D: ??? (in /usr/bin/convert-im6.q16)
==166847==  Address 0x7ea3300 is 384 bytes inside a block of size 4,096 alloc'd
==166847==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==166847==    by 0x4CEAC23: _IO_file_doallocate (filedoalloc.c:101)
==166847==    by 0x4CED812: setvbuf (iosetvbuf.c:60)
==166847==    by 0x48B580B: OpenBlob (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==166847==    by 0x4865C90: ??? (in /usr/lib/x86_64-linux-gnu/ImageMagick-6.9.11/modules-Q16/coders/pnm.so)
==166847==    by 0x48ECEEC: WriteImage (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==166847==    by 0x48ED905: WriteImages (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==166847==    by 0x4B7D9BC: ConvertImageCommand (in /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.6.0.0)
==166847==    by 0x4BE8C1E: MagickCommandGenesis (in /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.6.0.0)
==166847==    by 0x10917D: ??? (in /usr/bin/convert-im6.q16)
==166847==    by 0x4C95D8F: (below main) (libc_start_call_main.h:58)
==166847== 
P7
#
#P111���
#P11�2��2�~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~�~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~�~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WIDTH 2
HEIGHT 2
DEPTH 3
MAXVAL 255
TUPLTYPE RGB
ENDHDR
convert-im6.q16: unexpected end-of-file `../corruptedoutputheader': Invalid argument @ error/viff.c/ReadVIFFImage/758.
==166847== 
==166847== HEAP SUMMARY:
==166847==     in use at exit: 19,300 bytes in 19 blocks
==166847==   total heap usage: 4,529 allocs, 4,510 frees, 2,431,138 bytes allocated
==166847== 
==166847== LEAK SUMMARY:
==166847==    definitely lost: 0 bytes in 0 blocks
==166847==    indirectly lost: 0 bytes in 0 blocks
==166847==      possibly lost: 0 bytes in 0 blocks
==166847==    still reachable: 19,300 bytes in 19 blocks
==166847==         suppressed: 0 bytes in 0 blocks
==166847== Rerun with --leak-check=full to see details of leaked memory
==166847== 
==166847== Use --track-origins=yes to see where uninitialised values come from
==166847== For lists of detected and suppressed errors, rerun with: -s
==166847== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

If you save the outputted image data and run it multiple times youll see garbage output.

### Steps to Reproduce

convert corruptoutputheader PAM:-
Works with distro provided package and IM6 head from here.

### Images

[corruptedoutputheader.zip](https://github.com/ImageMagick/ImageMagick6/files/9543660/corruptedoutputheader.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
