### ISSUE TITLE
TIFF not rendered correctly

### ISSUE THREAD

**Issue by Lastique** [ImageMagick/ImageMagick6#198]
### ImageMagick version

6.9.2.64

### Operating system

Linux

### Operating system, version and so on

Kubuntu 22.04, Debian 11

### Description

TIFF images are not decoded correctly, the decoded image is corrupted.

This is a regression since 6.2.12.52, which did not have this problem.

### Steps to Reproduce

```
convert-im6.q16 640x480.tif 640x480-1.bmp
```

### Images

The original image (decompress with `gzip -d 640x480.tif.gz`): 
[640x480.tif.gz](https://github.com/ImageMagick/ImageMagick6/files/9699487/640x480.tif.gz)

Converted image (decompress with `gzip -d 640x480-1.bmp.gz`): 
[640x480-1.bmp.gz](https://github.com/ImageMagick/ImageMagick6/files/9699501/640x480-1.bmp.gz)

The two images should look the same, but the BMP looks corrupted.

**Comment by dlemstra** [comment]
We just applied a patche and this should be resolved in the next release.
