### ISSUE TITLE
ERROR_DELEGATE error persists until application is restarted

### ISSUE THREAD

**Issue by KernelDeimos** [ImageMagick/ImageMagick6#2]
I have a program written in Go using the gographics/imagick binding. I'm not entirely sure where this problem occurs as it could be the Go binding, the magicwand library, or the core library, based on my understanding. My program takes a PDF and uses this library to convert each page into an image (for display in a browser).

The problem I'm experiencing is not the fact that ImageMagick couldn't run Ghostscript (that could be for a number of reasons, including RAM usage - I'm not sure yet), but that as soon as the error happens once, it then persists until my program (an HTTP server) is restarted. I assume this means there's a global state that's affected by the error occurring the first time.

I posted a similar issue on the GitHub repo for the Go binding:
https://github.com/gographics/imagick/issues/164

This is the error message I receive:
```
ERROR_DELEGATE: FailedToExecuteCommand `"gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r200x200"  "-sOutputFile=/tmp/magick-24400PpSXLyVuSma4%d" "-f/tmp/magick-24400QWICA9Cnlcm4" "-f/tmp/magick-24400qFq7Wa4N4ay4"' (-1) @ error/delegate.c/ExternalDelegateCommand/461
```

**Comment by urban-warrior** [comment]
ImageMagick requires the Ghostscript delegate program or library to interpret Postscript.  Do you have Ghostscript installed on your system?  From the command-line does `gs -v` return the Ghostscript version?  If not, install Ghostscript and try your workflow again.  If it is installed, make sure its in the execution path of your HTTP server or modify IM's delegate.xml configuration file and change the relative 'gs' to the absolute path (e.g. /usr/local/bin/gs).
