### ISSUE TITLE
Webp image upload issue

### ISSUE THREAD

**Issue by SRIKANTHAR** [ImageMagick/ImageMagick6#203]
### ImageMagick version

6.9.10-23

### Operating system

Other (enter below)

### Operating system, version and so on

Ubuntu 20.04.5 LTS

### Description

webp images upload not supported it's giving this error message when trying to upload webp images has below

avatar_2_3_webp = open(image_ur)

at paperclip method "open" we are getting this error

ImageSpec::Error (#Paperclip::Tempfile:/tmp/18c5a2261d1d178068acb724a8a967b720221108-1242657-rpwwg520221108-1242657-n7zd3k.webp is not a supported image format. Sorry bub :():

we are using Rails 4.2 and ruby 2.3.0
paperclip (4.2.4)
paperclip-compression (0.3.11)
paperclip-optimizer (2.0.0)
ImageMagick 6.9.10-23

please help on this to how to fix this issue

### Steps to Reproduce

for jpeg and png upload working fine but when try upload webp its giving error. we config webp format also in code

**Comment by dlemstra** [comment]
This looks like an error from paperclip and I think that your build of ImageMagick is build without webp support.

**Comment by SRIKANTHAR** [comment]
Yes in command-line ImageMagick working for webp also ImageMagick converting jpg to webp in command-line

**Comment by dlemstra** [comment]
You will need to report this somewhere else then. We do not maintain the paperclip library.
