### ISSUE TITLE
ImageMagick6 uses incorrect registry lookup path for CodeModulesPath

### ISSUE THREAD

**Issue by RobertTheSable** [ImageMagick/ImageMagick6#204]
### ImageMagick version

6.9.12-67

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

ImageMagick6 is non-functional after installation on Windows due to a mismatch in the registry path used for CoderModulesPath. The installer puts the value in `HKEY_LOCAL_MACHINE\SOFTWARE\ImageMagick\Current`, but IM only looks for it directly under `HKEY_LOCAL_MACHINE` and `HKEY_CURRENT_USER`.

I tested with 3 different versions of the "DLL" version of ImageMagick6 (ImageMagick-6.9.12-67-Q16-x64-dll, ImageMagick-6.9.12-67-Q8-x64-dll, and ImageMagick-6.9.12-67-Q16-HDRI-x64-dll) and they all had this issue.

I was able to work around the issue by manually setting the key value under `HKEY_CURRENT_USER`.

### Steps to Reproduce

- Install ImageMagick-6.9.12-67-Q16-x64-dll, ImageMagick-6.9.12-67-Q8-x64-dll, or ImageMagick-6.9.12-67-Q16-HDRI-x64-dll
- Try to run any command using convert

**Comment by dlemstra** [comment]
It looks like I made a mistake when making the same change in IM6 that I made in IM7. I just pushed a patch that should fix this in the next release.

**Comment by RobertTheSable** [comment]
This seems to be fixed in ImageMagick-6.9.12-Q16-HDRI.
