### ISSUE TITLE
.HEIC colors wrong

### ISSUE THREAD

**Issue by jidanni** [ImageMagick/ImageMagick6#211]
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

Debian Sid

### Description

The colors are much different than the original.
The problem is in the display command, not the convert command.

### Steps to Reproduce

```
wget https://upload.wikimedia.org/wikipedia/commons/2/2d/Chunu_Bay%2C_Kanaga_Island%2C_Alaska.jpg
convert Chunu_Bay,_Kanaga_Island,_Alaska.jpg C.heic
display C.heic
```

**Comment by urban-warrior** [comment]
We're not seeing that.   Let's increase the image compression quality with

```
$ convert Chunu_Bay,_Kanaga_Island,_Alaska.jpg -quality 100 C.heic
$ compare -metric rmse Chunu_Bay,_Kanaga_Island,_Alaska.jpg C.heic  null:
20.7363 (0.000316416)
```

That's a relatively small distortion suggesting very similar pixel colors.  When we display both images (JPEG, HEIC), they look very similar in color as expected.

**Comment by jidanni** [comment]
All I know is one looks pink! The .heic:
![20230129T165021](https://user-images.githubusercontent.com/1230959/215315670-502f6986-8d35-458d-a039-e32cc6c0bd35.jpg)
![20230129T164950](https://user-images.githubusercontent.com/1230959/215315678-48b47dbe-fcb8-4f1d-b934-bf031a6bcfbd.jpg)

**Comment by jidanni** [comment]
$ convert Chunu_Bay,_Kanaga_Island,_Alaska.jpg -quality 100 C.heic
$ compare -metric rmse Chunu_Bay,_Kanaga_Island,_Alaska.jpg C.heic  null:
5098.55 (0.0777989)

**Comment by dlemstra** [comment]
Can you reproduce this with the latest version of ImageMagick?

**Comment by jidanni** [comment]
I wouldn't be here if Debian and would kindly install that one day.

**Comment by dlemstra** [comment]
As we are getting different results I will have to assume that this was fixed in the most recent version and I will close this issue.
