### ISSUE TITLE
Invalid JPG is now opened

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick6#213]
### ImageMagick version

6.9.12-73

### Operating system

Linux

### Operating system, version and so on

commit >= 007db884fa1977451488ab93284aae8f8ee851ca

### Description

In this commit https://github.com/ImageMagick/ImageMagick6/commit/007db884fa1977451488ab93284aae8f8ee851ca a few lines of code were removed, that changed the behaviour when opening invalid JPGs through the MagickWand api.

Before that commit, the image would fail to load, and an exception would be thrown by Imagick, presumable as it didn't get an error code back from the MagickWand API. After the change, the image would "be loaded" but be zero width and height

Was this change intentional?

First reported downstream at https://github.com/Imagick/imagick/issues/580

### Steps to Reproduce

The code below exits with error on commit 24706d1ed4149abadf7062a3dada1958db950111 and doesn't on commit
007db884fa1977451488ab93284aae8f8ee851ca:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <wand/MagickWand.h>
#include <wand/magick-image.h>

void ThrowWandException(MagickWand *wand) {
    char *description; 
    ExceptionType severity; 
    description = MagickGetException(wand, &severity); 
    (void) fprintf(stderr,"%s %s %lu %s\n",GetMagickModule(),description); 
    description=(char *) MagickRelinquishMemory(description); 
    exit(-1); 
}

int main(int argc,char **argv) {

    MagickBooleanType status;

    MagickWand *magick_wand, *canvas_wand;
    MagickWand *channel1_wand, *channel2_wand, *channel3_wand;


    MagickWandGenesis();
    magick_wand = NewMagickWand();
    status = MagickReadImage(magick_wand, "broken-image.jpg");
    if (status == MagickFalse) {
        ThrowWandException(magick_wand);
    }

    int width = MagickGetImageWidth(magick_wand);
    int height = MagickGetImageHeight(magick_wand);

    printf("width is %d, %d", width, height);

    MagickWandTerminus();

    return(0);
}
```

### Images

Image as zip to prevent it being mangled.
[broken-image.jpg.zip](https://github.com/ImageMagick/ImageMagick6/files/10512820/broken-image.jpg.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by vpv-csc** [comment]
We are seeing this bug with Alma 9 when running tests for our project https://github.com/Digital-Preservation-Finland/file-scraper

Alma 9 (EPEL 9) has ImageMagick 6.9.12.86. The file which causes the crash is https://github.com/Digital-Preservation-Finland/file-scraper/blob/master/tests/data/image_jpeg/invalid_1.01_data_changed.jpg

I can replicate the crash with Wand 0.6.11 with the following Python code:
```
import wand.image

results = wand.image.Image(filename="invalid_1.01_data_changed.jpg")
for image in results.sequence:
    pass
```

Running that script looks like this:
```
$ python3 wand-test.py 
python3: magick/image.c:787: CloneImage: Assertion `image != (const Image *) NULL' failed.
Aborted (core dumped)
```

Could you also fix this in ImageMagick 6?
