### ISSUE TITLE
Can't read XCF, "memory allocation failed"

### ISSUE THREAD

**Issue by Skif-off** [ImageMagick/ImageMagick6#215]
### ImageMagick version

6.9.11.60

### Operating system

Linux

### Operating system, version and so on

Xubuntu 22.04

### Description

Error message:
```
ImageMagic: memory allocation failed '/path-to-Untitled.xcf' @ error/xcf.c/ReadXCFImage/1366
```

### Steps to Reproduce

Try
```
convert-im6.q16 ./file.xcf file.png
```
where `file.xcf` is any XCF file created with GIMP 2.10.0+.

### Images

[test.xcf.zip](https://github.com/ImageMagick/ImageMagick6/files/10541856/test.xcf.zip)

**Comment by dlemstra** [comment]
Can you produce this issue with the latest version of ImageMagick? And please attach an image that can be used to reproduce this issue.

**Comment by Skif-off** [comment]
@dlemstra, now I have tried several versions (build with default options):
6.9.12-20: error;
6.9.12-75: error;
7.1.0-60: works fine.

> And please attach an image

Ok.

**Comment by dlemstra** [comment]
Just realized that we did not add support for reading GIMP 2.10+ files to ImageMagick 6. I would advise you to switch to ImageMagick 7 instead.
