### ISSUE TITLE
Convert command always taking policy from global policy.xml file instead of custom path

### ISSUE THREAD

**Issue by hctpbl** [ImageMagick/ImageMagick6#22]
### Description
I use ImageMagick to convert pdf files to png, the ImageMagick version I am using (6.8.9-9) ships with a default `policy.xml` file that has no permissions for reading PDF files. I changed that `policy.xml` file and everything is working correctly, but I want to be able to have my own `policy.xml` file in a path of my choice that I can ship with my project, so I can deploy the project in a new server without having to configure the server's default `policy.xml` file every time.

According to [ImageMagick v6 documentation ](https://legacy.imagemagick.org/script/resources.php) the policy will be looked for in the following locations (I'm using the precompiled binary installation for Ubuntu 16.04):

```
$MAGICK_CONFIGURE_PATH
$MAGICK_HOME/etc/ImageMagick-6 
$MAGICK_HOME/share/ImageMagick-6 
$PREFIX/share/ImageMagick-6 
$XDG_CACHE_HOME/ImageMagick
$HOME/.config/ImageMagick/
<client path>/etc/ImageMagick
<current directory>
```

So I set the env variable `MAGICK_CONFIGURE_PATH` to the path I put my policy file on. I would expect the `convert` command to find it there and use that policy to execute, but it seems to be using the one in `/etc/ImageMagick-6` anyway. The policy file is correctly found when using the command to list the policy:

```
$convert -list policy

Path: /home/<user>/path/to/file/policy.xml
  Policy: undefined
    rights: None 
  Policy: Coder
    rights: None 
    pattern: EPHEMERAL
  Policy: Coder
    rights: None 
    pattern: URL
  Policy: Coder
    rights: None 
    pattern: HTTPS
  Policy: Coder
    rights: None 
    pattern: MVG
  Policy: Coder
    rights: None 
    pattern: MSL
  Policy: Coder
    rights: None 
    pattern: TEXT
  Policy: Coder
    rights: None 
    pattern: SHOW
  Policy: Coder
    rights: None 
    pattern: WIN
  Policy: Coder
    rights: None 
    pattern: PLT
  Policy: Path
    rights: None 
    pattern: @*
  Policy: Coder
    rights: None 
    pattern: PS
  Policy: Coder
    rights: None 
    pattern: EPS
  Policy: Coder
    rights: Read 
    pattern: PDF
  Policy: Coder
    rights: None 
    pattern: XPS

Path: /etc/ImageMagick-6/policy.xml
  Policy: undefined
    rights: None 
  Policy: Coder
    rights: None 
    pattern: EPHEMERAL
  Policy: Coder
    rights: None 
    pattern: URL
  Policy: Coder
    rights: None 
    pattern: HTTPS
  Policy: Coder
    rights: None 
    pattern: MVG
  Policy: Coder
    rights: None 
    pattern: MSL
  Policy: Coder
    rights: None 
    pattern: TEXT
  Policy: Coder
    rights: None 
    pattern: SHOW
  Policy: Coder
    rights: None 
    pattern: WIN
  Policy: Coder
    rights: None 
    pattern: PLT
  Policy: Path
    rights: None 
    pattern: @*
  Policy: Coder
    rights: None 
    pattern: PS
  Policy: Coder
    rights: None 
    pattern: EPS
  Policy: Coder
    rights: None 
    pattern: PDF
  Policy: Coder
    rights: None 
    pattern: XPS

Path: [built-in]
  Policy: Undefined
    rights: None 
```

But I get a not authorized error. If I change the policy file in `/etc/ImageMagick-6/policy.xml` to allow reading PDF files, my convert command works.

I have also tried to place the policy file in the `<current directory>` from where I call the convert command, it also appears when I execute `convert -list policy`, but I still get the not authorized error unless I changed the global policy file.

### System Configuration

- ImageMagick version: 6.8.9-9
- Environment (Operating system, version and so on): Ubuntu 16.04.4

**Comment by dlemstra** [comment]
@hctpbl Might be nice for future users to know why you closed this issue.
