### ISSUE TITLE
Test suite should have  a verbose mpde

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick6#221]
### ImageMagick version

6

### Operating system

Linux

### Operating system, version and so on

debian

### Description

Hi,

It is for now impossible to get a verbose output (command excecuted) for the test suite

Could be possible by adding a some env variable to be verbose 

### Steps to Reproduce

make check is not verbose

**Comment by dlemstra** [comment]
Feel free to open a pull request to do that.

**Comment by urban-warrior** [comment]
For verbose, run the test suite outside of TAP:

```
$ cd tests
$ ./validate  -validate formats-memory
Version: ImageMagick 7.1.1-8 Q16-HDRI x86_64 21130 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC

ImageMagick Validation Suite (FormatsMemory)

[pixel-cache: memory] validate image formats in memory:
  test 0: ART/Undefined/TrueColor/8-bits... pass
  test 1: ART/Undefined/TrueColorAlpha/8-bits... pass
  test 2: ART/Undefined/Grayscale/8-bits... pass
  test 3: ART/Undefined/GrayscaleAlpha/8-bits... pass
...
```

**Comment by bastien-roucaries** [comment]
Thanks solved
