### ISSUE TITLE
Reading PSD layers (except first) discards profile information

### ISSUE THREAD

**Issue by jonsneyers** [ImageMagick/ImageMagick6#23]
When doing something like `convert foo.psd[1] output.jpg`, any color profile or other metadata that was in the PSD is lost. This is a regression w.r.t. version 6.9.8, where it would (correctly) preserve that information.

(I think TIFF has the same problem, but PDF is fine)

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick6 later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
