### ISSUE TITLE
Uncaught ImagickException: insufficient image data in file `/tmp/magick-5054YuqrlU0SzTeO'

### ISSUE THREAD

**Issue by kdgeorgiev** [ImageMagick/ImageMagick6#233]
### ImageMagick version

6.9.7

### Operating system

Linux

### Operating system, version and so on

CentOS7

### Description

When trying to load a generic page I get the following error.

```
Fatal error: Uncaught ImagickException: insufficient image data in file /tmp/magick-5054i7cT1EQFO5nV @ error/jpeg.c/ReadJPEGImage/1156 in /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-editor.class.php:39 

Stack trace: 
#0 /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-editor.class.php(39): Imagick->__construct('s3eucentral1://...') 
#1 /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-generator.php(70): TheGem_Dummy_WP_Image_Editor->get_size() 
#2 /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-generator.php(63): thegem_build_image_data('s3eucentral1://...') 
#3 /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-generator.php(26): thegem_get_thumbnail_src(196, 'thegem-gallery-...') 
#4 /home/troshevadm/public_html/wp-content/plugins/thegem-elements-elementor/thegem-elements-elementor.php(288): thegem_generate_thumbnail_sr in /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-editor.class.php on line 39
```

### Steps to Reproduce

Created a theme, added images and now getting the error.

### Images

<img width="698" alt="Screenshot 2023-04-12 at 22 49 04" src="https://user-images.githubusercontent.com/60313259/231568955-d6fbb8d3-cc6d-44ee-95a7-878b5c80a758.png">

**Comment by kdgeorgiev** [comment]
Okay!

Went into my cli and decided to remove the ImageMagick 6 ext.

`Removed:
  ImageMagick.x86_64 0:6.9.10.68-6.el7_9                                                                                                                                                    

Dependency Removed:
  ImageMagick-devel.x86_64 0:6.9.10.68-6.el7_9                                                                                                                                              

Complete!`

Now the fatal error is no longer active. I need the ImageMagick dependencies for this plugin.
[Color Fixer](https://github.com/CreunaFI/color-space-fixer)

Let me try to remove and clean completely the dependency ImageMagick and Color Fixer. Then I would install it and see if it gives me the same error.

**Comment by dlemstra** [comment]
Your input image is invalid and that is why ImageMagick will refuse to read it.
