### ISSUE TITLE
Unable to convert 1bpp png file

### ISSUE THREAD

**Issue by ASRoden** [ImageMagick/ImageMagick6#239]
### ImageMagick version

6.9.10-68

### Operating system

Linux

### Operating system, version and so on

CentOS Linux 7

### Description

I am unable to use imagemagick to convert and existing 1 bit per pixel .png file.
/usr/bin/convert test.png out.bmp returns
Get a no images defined 'out.bmp' @ error/convert.c/ConvertImageCommand/3235

### Steps to Reproduce

have a 1bpp test.png file
call /usr/bin/convert test.png out.bmp

### Images

![test png](https://user-images.githubusercontent.com/132925554/236866851-9a758032-cb33-4fc5-b202-d04631683f73.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
