### ISSUE TITLE
ImageMagick 6.9.12-82 use built-in ghostscript instead of newer version

### ISSUE THREAD

**Issue by sonvt-seta** [ImageMagick/ImageMagick6#240]
### ImageMagick version

6.9.12-82

### Operating system

Linux

### Operating system, version and so on

CentosOS8

### Description

I create a docker file with CentosOS base64 with Ghostscript 9.56.1 and ImageMagick 6.9.12-82 but when run 
```
convert a.eps a.jpg
```

the Ghostscript version used is 9.27

I also change the `gs` in delegates.xml but it does not work

Dockerfile
```
FROM centos:centos8

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
RUN dnf install centos-release-stream -y
RUN dnf swap centos-{linux,stream}-repos -y
RUN dnf distro-sync -y
RUN dnf clean all && rm -r /var/cache/dnf && yum -y update
RUN yum -y install epel-release javapackages-tools
RUN yum -y groupinstall "Development Tools"

RUN mkdir ~/ghostscript
RUN curl -L https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs9561/ghostscript-9.56.1.tar.xz -o ~/ghostscript/ghostscript-9.56.1.tar.xz
RUN tar -xf ~/ghostscript/ghostscript-9.56.1.tar.xz -C ~/ghostscript
RUN cd ~/ghostscript/ghostscript-9.56.1 && ./configure
RUN cd ~/ghostscript/ghostscript-9.56.1 && make
RUN cd ~/ghostscript/ghostscript-9.56.1 && make install
RUN mkdir /usr/local/share/ghostscript/fonts
RUN cp ~/ghostscript/ghostscript-9.56.1/Resource/Font/* /usr/local/share/ghostscript/fonts
RUN rm -r ~/ghostscript

RUN cp /usr/local/bin/gs /usr/local/gs
RUN yum install -y \
      ImageMagick ImageMagick-devel

CMD ["/bin/bash"]
```

Delegate And Configure

[delegates.txt](https://github.com/ImageMagick/ImageMagick/files/11427889/delegates.txt)

[configure.txt](https://github.com/ImageMagick/ImageMagick/files/11427891/configure.txt)

### Steps to Reproduce

convert -debug all -verbose a.eps a.jpg
![image](https://user-images.githubusercontent.com/83684250/237008804-e2b5f358-7b67-4061-9cc3-fb46ffc87ef5.png)

### Images

![image](https://user-images.githubusercontent.com/83684250/237008970-cf576a15-3cf6-4567-ac2d-dff1c006d11f.png)

**Comment by dlemstra** [comment]
This is probably related to installing ImageMagick with `yum` at the end of your `Dockerfile`. It seems that that version of ImageMagick is build with `gslib`. What happens when you first install ImageMagick and then build and install Ghostscript?

**Comment by sonvt-seta** [comment]
I also try install ImageMagick first and then build and install Ghostscript but still the same

**Comment by dlemstra** [comment]
What is the output of `ldd magick`? It should show a link to a gslib file. That is probably different from the one that was created when you build Ghostscript.

**Comment by dlemstra** [comment]
Is the ghostscript library file also installed in /lib64? The one that you build yourself.

**Comment by sonvt-seta** [comment]
No, It's in /usr/local/bin/gs.

**Comment by dlemstra** [comment]
I mean the `libgs.so.9` file. You will need to overwrite the library with a newer version from your ghostscript build.

**Comment by sonvt-seta** [comment]
I don't think there's any `libgs` file in the docker

![image](https://github.com/ImageMagick/ImageMagick6/assets/83684250/29d98d7c-53ff-4a6a-893c-526abd1a38e1)

**Comment by dlemstra** [comment]
There should be one somewhere because you seem to be using it when running `convert`.

**Comment by sonvt-seta** [comment]
Yeah. I try to find this but don't have any progress.

**Comment by dlemstra** [comment]
The `find` command requires wildcards: `find / -name libgs.so.*`. And then you will find the libraries. But it looks like you will need to also build Ghostscript differently with `make so` to make sure the libraries are build. And then you will need to also overwrite the `libgs.so.9` file that is used by `convert` with `ln -s libgs.so.9.56 libgs.so.9`. I gave that a try but ended up with an internal error in Ghostscript. My advise would also be to make sure you are using the latest version of Ghostscript due to security issues in that library.

**Comment by sonvt-seta** [comment]
Thanks for your advice. The ImageMagick uses correct Ghostscript version now 
![image](https://github.com/ImageMagick/ImageMagick6/assets/83684250/41b1afe9-a80f-470d-89e2-89126d5237ef)
