### ISSUE TITLE
`convert`: wrong file used for input

### ISSUE THREAD

**Issue by brunoais** [ImageMagick/ImageMagick6#241]
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

ubuntu 22.04c (linux 6.1.0)

### Description

Given a directory with 2 files:

```
-rw-rw-r-- 1 me me  4295 today imagea.png
-rw-rw-r-- 1 me me 45604 today imageb.png
```

If I try to convert to convert imageb to webp, `convert` converts imagea instead.
If I remove imagea, `convert` correctly converts the only file in the directory (imageb)

### Steps to Reproduce

1. Execute: `convert './imageb.png' -quality 100 -define webp:lossless=true imageb_l.webp`
2. imagea was converted instead of imageb

### Images

![imagea](https://github.com/ImageMagick/ImageMagick6/assets/639467/240c20c4-84e1-42e8-ac41-f0e4dc27b16d)
![imageb](https://github.com/ImageMagick/ImageMagick6/assets/639467/46e7ffe7-c649-498a-b3c5-a77dcdb8cdea)

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce the issue.  Your command works as expected for us.  Add `-verbose` to your command line and post the output of the command here.

**Comment by brunoais** [comment]
`-verbose` shows a perfectly normal output.
```
$ convert -verbose './imageb.png' -quality 100 -define webp:lossless=true imageb_l.webp
./imageb.png PNG 2338x3441 2338x3441+0+0 8-bit sRGB 45604B 0.100u 0:00.134
./imageb.png=>imageb_l.webp PNG 2338x3441 2338x3441+0+0 8-bit sRGB 8784B 0.180u 0:00.335
```

Seems like there's more to it. Seems like this happens when there's a gvfs path in the way. E.g.
`/run/user/1000/gvfs/sftp:host=remotehost,user=myRemoteUserUsername/path/toDirectory/file`

but if I make a symlink to that gvfs directory locally (E.g. `cd /home/user/path/symlinkName/toDirectory/file; ln -s '/run/user/1000/gvfs/sftp:host=remotehost,user=myRemoteUserUsername/path/' symlinkName` )

 so the path looks like a normal:
`/home/user/path/symlinkName/toDirectory/file`
the issue remains.

I tried connecting with gvfs to my own PC and whether the issue happens is a hit or miss. To a different PC (even if in the same network) appears to be easily reproducible.

Does this help?

**Comment by urban-warrior** [comment]
Type `convert -format | grep webp`.  Confirm you have the Webp delegate.

Try this command sequence:

```
$ cd /run/user/1000/gvfs/sftp:host=remotehost,user=myRemoteUserUsername/path/
$ convert rose: testa.png
$ convert logo: testb.png
$ convert -verbose './testb.png' -quality 100 -define webp:lossless=true testb.webp
$ compare -metric rmse testb.webp testb.png null:
```

If the last command returns a distortion of 0, the command is working as expected.  If not, something screwy is occurring as you suggest.

The next step would be to repeat the test with a GVFS path that does not include a colon, i.e., remove the `sftp:host`.

Finally, repeat the test with the latest release of ImageMagick 6, 6.1.12-88 to determine if the issue remains.  You could also try with the latest release of ImageMagick 7.

**Comment by brunoais** [comment]
> Type `convert -format | grep webp`. Confirm you have the Webp delegate.

Confirmed:
`Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib`


> Try this command sequence:

The command sequence you shown works and the image looks correct.

However, this sequence fails, for some reason:

```
$ cd /run/user/1000/gvfs/sftp:host=remotehost,user=myRemoteUserUsername/path/
$ convert rose: imagea.png
$ convert logo: imageb.png
$ convert -verbose './imageb.png' -quality 100 -define webp:lossless=true imageb.webp
./imageb.png PNG 640x480 640x480+0+0 8-bit sRGB 256c 27398B 0.010u 0:00.025
./imageb.png=>testb.webp PNG 640x480 640x480+0+0 8-bit sRGB 256c 22430B 0.050u 0:00.222
$ compare -metric rmse imageb.webp imageb.png null:
0 (0)
```
