### ISSUE TITLE
source_colorspace is not always initialized

### ISSUE THREAD

**Issue by itaibenari** [ImageMagick/ImageMagick6#25]
Here:
https://github.com/ImageMagick/ImageMagick6/blob/master/magick/profile.c#L976
`source_colorspace` is not initialized.
However, since the verification of the compatibility of `source_colorspace` and `image->colorspace` was removed, `source_colorspace` is just unused.
Any reason these validations were removed? https://github.com/ImageMagick/ImageMagick6/commit/c4d19516a81ee36450558cb766af9de111893a8c

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
