### ISSUE TITLE
Trying to convert SVG to PNG asks for potrace

### ISSUE THREAD

**Issue by Moini** [ImageMagick/ImageMagick6#250]
### ImageMagick version

6.9.11-60 Q16 x86_64 2021-01-25

### Operating system

Linux

### Operating system, version and so on

Linux Mint 21.1 Vera

### Description

I'm using a small script to convert files of different file types to thumbnails. 

It has stopped working properly after updating my Linux Mint version. After fixing an issue with find, which now needs a different order of commands, I'm now stuck on an issue with convert, which is for some weird reason wanting to use potrace to convert an SVG to an PNG.

This might totally be a Linux Mint default settings bug, too. I have Inkscape installed (1.2.2), and rsvg, too. 

### Steps to Reproduce

```
for f in $(find -maxdepth 2 -printf '%P\n' -iname '*.jpg' -o -iname '*.eps' -o -iname '*.png' -o -iname '*.svg' | grep -v '/thumbnails/')
do
  if [ ! -f ./thumbnails/$f.png ]
  then
    echo "Creating thumbnail for $f"
    convert $f -background white -alpha remove -thumbnail 220x180\> - | convert - -gravity center -background "rgb(200,200,200)" -extent 240x200 -alpha remove ./thumbnails/$f.png
  fi
done
```

returns this for any SVG file (works for pngs, jpgs):

```
Creating thumbnail for 2023/mini-poster_kielux_2023_portrait.svg
convert-im6.q16: delegate failed `'potrace' --svg --output '%o' '%i'' @ error/delegate.c/InvokeDelegate/1966.
convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/575.
convert-im6.q16: no images defined `./thumbnails/2023/mini-poster_kielux_2023_portrait.svg.png' @ error/convert.c/ConvertImageCommand/3229.
```

**Comment by urban-warrior** [comment]
Type `convert -list format | grep PNG`.  Does the PNG format have a mode of `rw-`?  If not, your ImageMagick build does not include PNG support so ImageMagick defaults to the input file type, SVG.  When writing SVG, it leverages `potrace` to generate a SVG representation of the image pixels.

**Comment by Moini** [comment]
Thanks, @urban-warrior - but that's not the reason:

![grafik](https://github.com/ImageMagick/ImageMagick6/assets/3240233/f178254b-6837-4c5a-a023-e25336232269)

**Comment by dlemstra** [comment]
`convert $f -background white -alpha remove -thumbnail 220x180\> -` will try to write with svg as the output format.

**Comment by Moini** [comment]
@dlemstra But why would potrace be needed to scan an SVG image to add a white background and resize the image? Wouldn't that be a job for Inkscape instead?

**Comment by dlemstra** [comment]
ImageMagick needs a tool to write an intermediate image `svg` image as you are instructing it to do. And that is why we need to use `autotrace`.

I don't know much about `inkscape` but maybe you could only use that instead of ImageMagick.

**Comment by Moini** [comment]
autotrace != potrace, and the SVG is already an SVG, so converting to raster and back doesn't make too much sense. 

But yes, it would be an option to use just Inkscape alone for SVG files in my script.

**Comment by dlemstra** [comment]
Sorry I meant to write `potrace`. ImageMagick internally uses a raster image. So when it reads a vector image it first converts it to a raster image. And when you ask it to write a vector image it will need a tool to convert a raster image to a vector image.

**Comment by Moini** [comment]
Yep, got it! Thank you!
