### ISSUE TITLE
we don't have the tag 6.9.12-91 in github repo

### ISSUE THREAD

**Issue by sergiomb2** [ImageMagick/ImageMagick6#256]
### ImageMagick version

6.9.12-91

### Operating system

Linux

### Operating system, version and so on

Fedora

### Description

Hi,
https://github.com/ImageMagick/ImageMagick6/commit/3d0f45a2af79d483aae3beab9b3be2401064ba5a was done but tag doesn't exist yet , what happened ? 

Thank you

### Steps to Reproduce

also for example ImageMagick-6.9.12-91 is available on fossies https://fossies.org/linux/misc/ImageMagick-6.9.12-91.tar.xz/

**Comment by dlemstra** [comment]
This is a manual process and sometimes takes a couple days to show up. We will add the tag later today.
