### ISSUE TITLE
Identify with format switch reports erroneous JPEG quality if actual value is undefined

### ISSUE THREAD

**Issue by bitsgalore** [ImageMagick/ImageMagick6#260]
### ImageMagick version

6.9.10-23

### Operating system

Linux

### Operating system, version and so on

Linux Mint 20.1 Ulyssa

### Description

Identify with *format* switch reports erroneous JPEG quality fallback value if actual value is undefined.

### Steps to Reproduce

Attached JPEG file was supplied to us by a vendor, who claims it was compressed at 50% quality. In an attempt to verify this claim, I first ran *identify* with verbose output: 

```
identify -verbose test-quality.jpg
```

The resulting output does not contain the "Quality" property (which is used for JPEG quality). So for some reason *identify* doesn't seem to be able to establish the quality level in this case (I'm not entirely sure why, but from what I read [here](https://fotoforensics.com/tutorial-estq.php) estimating JPEG quality can be tricky at low quality levels). But if I run *identify* like this (which *only* reports the quality level):

```
identify -format '%Q\n' test-quality.jpg
```

Result:

```
92
```

Which is obviously wrong in this case! The actual file size is actually pretty much what I would expect for a 50% quality JPEG for this kind of material; also a double-check with [this tool by Neal Krawetz](https://www.hackerfactor.com/src/jpegquality.c) confirmed the actual quality must be quite low.

I had a quick look into the code, and found this:

<https://github.com/ImageMagick/ImageMagick/blob/f5bdfdd62af7109ad105f8af4e28111e353edecd/MagickCore/property.c#L2725>

I'm not a C programmer, but if I understand this correctly, this forces the reported image quality to a "92" fallback value if the actual quality is 0 (I assume this is used internally if the actual quality cannot be determined). If I'm correct, a better solution may be to use something that clearly indicates that the quality level is undefined here.

(Side note: I also did some additional tests with low-quality JPEGs I made within ImageMagick, but for all of these *identify* was able to report the correct quality value. It's not clear to me why this is the case.)   

### Images

![test-quality](https://github.com/ImageMagick/ImageMagick/assets/1014449/bdf17e14-c697-4f4a-b6d5-e3067e0afc08)

**Comment by bitsgalore** [comment]
@fmw42  You're probably right, but IM's current behavior makes it impossible to distinguish between JPEGs that were actually compressed at 92% quality, and JPEGs for which the quality is unknown, which isn't very helpful. Reporting some NaN value or even an empty string (I don't know if there are any IM conventions for this?) would be much more helpful: knowing that IM cannot establish the quality is actually useful information!

BTW  you mention the absence of quality level info in the metadata. I noticed that as well. From the [Fotoforensics explainer](https://fotoforensics.com/tutorial-estq.php) (tab "Estimating Quality) I understand it's quite rare for JPEGs to have this info in the metadata, and even if it's there, it's often unreliable. It's not entirely clear to me how IM establishes the quality; I *suspect* somewhere under the hood IM or some delegate library uses either the "Approximate Ratios" or "Approximate Quantization Tables" methodsl. But from the code I can't quite figure out if this is the case.

However, JPEGs created inside IM don't appear to contain quality-related metadata either. Nevertheless, "identify" *is* able to establish the quality! 

A quick example. First I create a new JPEG with 40% compression quality: 

```
convert -quality 40 wizard: wizard-40.jpg
```

The output of the following ExifTool command doesn't contain anything related to the quality level:

```
exiftool -X wizard-40.jpg
```

Despite this, using "identify":

```
identify -format '%Q\n' wizard-40.jpg
```

Result:

```
40
```

This is all slightly straying from the issue, which is really about the *reporting*. But since it popped up in the conversation, and I'd be doing some tests with that already, I might as well mention it in case it's of any use.

**Comment by bitsgalore** [comment]
A bit of further digging confirmed that IM actually determines the JPEG compression quality from the quantization tables, and not from some pre-defined metadata field:

<https://github.com/ImageMagick/ImageMagick6/blob/bf9bc7fee9f3cea9ab8557ad1573a57258eab95b/coders/jpeg.c#L925>

**Comment by bitsgalore** [comment]
For info - I did some further tests with a Python port of ImageMagick's JPEG quality heuristic. See below blog post for details:

<https://www.bitsgalore.org/2024/10/23/jpeg-quality-estimation-experiments-with-a-modified-imagemagick-heuristic>

This explains why it doesn't come up with a quality estimate (see sections "ImageMagick’s JPEG quality heuristic" and "Tracing all loop variables").

In the same post I also tentatively propose a modified heuristic that works for low quality images that use non-standard quantization tables. I'm not entirely sure how much sense this makes, but I hope the post will provoke some responses from people who are better versed in in the inner workings of the JPEG compression algorithm.

All scripts and data I used for this are available here:

<https://github.com/KBNLresearch/jpeg-quality-demo>

**Comment by bitsgalore** [comment]
Another update - after some more testing I found additional problems with the quality heuristic, and ended up writing an alternative estimation procedure from scratch (also based on the standard quantization tables). Since this really is a separate issue I reported this under a new ticket here:

<https://github.com/ImageMagick/ImageMagick/issues/7732>

**Comment by dlemstra** [comment]
Closing this because of that new issue that was opened. This issue and that other issue are about the same thing.
