### ISSUE TITLE
Conversion errors for some .tif files with versions higher than 6.9.12-77

### ISSUE THREAD

**Issue by xImMoRtALitY99** [ImageMagick/ImageMagick6#261]
### ImageMagick version

6.9.12-78

### Operating system

Linux

### Operating system, version and so on

Debian 11.7

### Description

Converting a .tif file to a .jpeg file works successfully with ImageMagick 6.9.12-77, but looks incorrect with versions ImageMagick 6.9.12-78 and higher. The convert command runs successfully, but from version 6.9.12-78 the result looks much worse, as if there were problems with the conversion.

### Steps to Reproduce

If you use the image original.tif from the images.zip attachment, the conversion error should occur.

Version 6.9.12-77:
`convert --version`

> Version: ImageMagick 6.9.12-77 Q16 x86_64 c8a10adfe:20230211 https://legacy.imagemagick.org
> Copyright: (C) 1999 ImageMagick Studio LLC
> License: https://imagemagick.org/script/license.php
> Features: Cipher DPC Modules OpenMP(4.5)
> Delegates (built-in): bzlib freetype jbig jng jpeg lcms ltdl lzma png tiff webp xml zlib

`convert -verbose original.tif 77.jpeg`

> original.tif TIFF 1063x1063 1063x1063+0+0 8-bit ColorSeparation CMYK 1.29019MiB 0.090u 0:00.066
> original.tif=>77.jpeg TIFF 1063x1063 1063x1063+0+0 8-bit ColorSeparation CMYK 785193B 0.050u 0:00.054

Version 6.9.12-78 and higher:
`convert --version`

> Version: ImageMagick 6.9.12-78 Q16 x86_64 999ee5b55:20230307 https://legacy.imagemagick.org
> Copyright: (C) 1999 ImageMagick Studio LLC
> License: https://imagemagick.org/script/license.php
> Features: Cipher DPC Modules OpenMP(4.5)
> Delegates (built-in): bzlib freetype jbig jng jpeg lcms ltdl lzma png tiff webp xml zlib

`convert -verbose original.tif 78.jpeg`

> original.tif TIFF 1063x1063 1063x1063+0+0 8-bit ColorSeparation CMYK 1.29019MiB 0.070u 0:00.064
> original.tif=>78.jpeg TIFF 1063x1063 1063x1063+0+0 8-bit ColorSeparation CMYK 926801B 0.060u 0:00.061

### Images

[images.zip](https://github.com/ImageMagick/ImageMagick6/files/12360496/images.zip)

**Comment by dlemstra** [comment]
Looks like an issue in IM6, getting the correct output in IM7.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce the issue and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
