### ISSUE TITLE
Feature removal: display and/or file associations

### ISSUE THREAD

**Issue by usernamehyphen** [ImageMagick/ImageMagick6#262]
### Is your feature request related to a problem? Please describe.

Hi!
I undestand that ImageMagick is very powerfull commandline utility to manipulate images, but somehow it still also contains a gui part (display?) namely this file: /usr/share/applications/display-im6.q16.desktop (is it part of the repo or distro?) which associates itself with all known image formats, and is default to open them and it sucks a lot...

Ubuntu started their software center couple years ago, since then ImageMagick got its entry there (sorry, no URL) - its rating is about 1 :star: out of 5 and all reviews complain about it existing on their computers (it was probably installed as inkscape dependency)

### Describe the solution you'd like

rm /usr/share/applications/display-im6.q16.desktop
that would keep ImageMagick useable and maybe with less negative reviews in future.

### Describe alternatives you've considered

uninstalling Inkscape with all its dependencies.. but rm does the trick

**Comment by urban-warrior** [comment]
We do not support nor maintain Linux distro's.  To get any traction on this issue you would need to contact the Ubuntu maintainers.  Note, ImageMagick has a build option to omit the GUI and only install the image processing utilities such as `convert`.
