### ISSUE TITLE
ImageMagick incorrect crops gif file

### ISSUE THREAD

**Issue by Urozhaeva** [ImageMagick/ImageMagick6#264]
### ImageMagick version

6.9.12-93

### Operating system

Linux

### Operating system, version and so on

ALT Workstation K 10.1

### Description

ImageMagick incorrect crops gif file

### Steps to Reproduce

1. Crop gif file:
`$ convert *.gif -crop 100x100+0+0 file_conv.gif`

Actual result:
Only image was cropped, but not the whole file. See attachments below

[Initial_file_and_information_about_it.tar.gz](https://github.com/ImageMagick/ImageMagick6/files/12461892/Initial_file_and_information_about_it.tar.gz)
[Converted_file_and information_about_it.tar.gz](https://github.com/ImageMagick/ImageMagick6/files/12461898/Converted_file_and.information_about_it.tar.gz)

Expected result:
The whole gif file is croped

Please note behaviour isn't applicable to .bmp, .jpg, .pgm, .psd

**Comment by urban-warrior** [comment]
Perhaps you want to remove the virtual canvas: `convert *.gif -crop 100x100+0+0 -page 0x0+0+0 file_conv.gif`.
