### ISSUE TITLE
librsvg delegate is available but not used

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick6#274]
### ImageMagick version

6.9.12-96

### Operating system

Windows

### Operating system, version and so on

mingw-w64 (all flavours)

### Description

I maintain the R bindings. We use a static build of imagemagick6 with librsvg enabled. After we upgraded from 6.9.12-3 to 6.9.12-96, users started to notice that the librsvg delegate no longer works. 

When opening an svg file in C++ we get an error, indicating that imagemagick is trying to shell out to inkscape, instead of using the librsvg delegate.

```
Error: Rgui.exe: FailedToExecuteCommand `"inkscape" "C:/Users/jeroen/AppData/Local/Temp/Rtmps5vqwz/magick-TdJNLAFk_U1XA8dctHLrq5WWcOZt5TRb" --export-png="C:/Users/jeroen/AppData/Local/Temp/Rtmps5vqwz/magick-tdU9jouKoL2eyOZEphKhg87YXwL88CfO.png" --export-dpi="96" --export-background="rgb(100%,100%,100%)" --export-background-opacity="1" > "C:/Users/jeroen/AppData/Local/Temp/Rtmps5vqwz/magick-bnEjgemQtiZBXeXfsAZHAk-YOTwwcF6Y" 2>&1' (-1) @ error/delegate.c/ExternalDelegateCommand/514
```

This problem did not appear without old build (6.9.12-3). I double checked that the librsvg was built in, you can actually see the build logs here: https://github.com/r-windows/ucrt-libs/actions/runs/6289557157/job/17076154957

```
...
  RAW               --with-raw=yes		yes
  RSVG              --with-rsvg=yes		yes
  TIFF              --with-tiff=yes		yes
```

There seems to be a bug that imagemagick no longer uses the librsvg delegate to read svg files, even though it is available.
 

Perhaps relevant is that we use a static build with `--without-modules --enable-zero-configuration`, so there is no xml involved at runtime.

### Steps to Reproduce

In C++, open an svg file.

**Comment by dlemstra** [comment]
I just pushed a patch that should solve this.

**Comment by jeroen** [comment]
Thanks, that fixed it!
