### ISSUE TITLE
delegates.xml broken for dng:decode

### ISSUE THREAD

**Issue by crichmon762** [ImageMagick/ImageMagick6#276]
### ImageMagick version

6.9.11.60+dfsg-1.3+deb11u1

### Operating system

Linux

### Operating system, version and so on

Devuan chimaera (Debian Bullseye (11.1) with Linux kernel 5.10)

### Description

I used to be able to use display to open/manipulate .RW2 files.  After an OS upgrade, this failed with these errors like this:
> display -resize 40% RW2:P1020367.RW2
** Message: 19:53:50.254: Error in canonicalize_file_name('/tmp): No such file or directory
display-im6.q16: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 --output='%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1966.
display-im6.q16: unable to open image `/tmp/magick-JXd5S2fUce-Vj6vFsvWfPvkQx2gLznSf.ppm': No such file or directory @ error/blob.c/OpenBlob/2924.
After a bit of sleuthing, I found the backup before the upgrade and compared the delegates.xml entry for dng:decode.
router1:/etc/ImageMagick-6# grep dng delegates.xml
  <delegate decode="dng:decode" command="&quot;ufraw-batch&quot; --silent --create-id=also --out-type=png --out-depth=16 --output=&quot;%u.png&quot; &quot;%i&quot;"/>
  <delegate decode="dng:decode" command="&quot;ufraw-batch&quot; --silent --create-id=also --out-type=png --out-depth=16 &quot;--output=%u.png&quot; &quot;%i&quot;"/>
The issue appears to be the position of the &quot; in relation to --output.  Once I made the current delegates.xml entry match the original that was working in relation to --output, I was again able to display .RW2 files.

### Steps to Reproduce

See description;
The issue appears to be the position of the &quot; in relation to --output.  Once I made the current delegates.xml entry match the original that was working around --output, I was again able to display .RW2 files.

**Comment by dlemstra** [comment]
What did you change where?

**Comment by crichmon762** [comment]
So, the broken declaration is first and moved into the comments in the file. The fixed version

is second, and it’s this specific change:

< --output=&quot;%u.png&quot;

> &quot;--output=%u.png&quot; ß this one works

router1:/etc/ImageMagick-6# grep dng:decode delegates.xml

<delegate decode="dng:decode" command="&quot;ufraw-batch&quot; --silent --create-id=also --out-type=png --out-depth=16 --output=&quot;%u.png&quot; &quot;%i&quot;"/>

<delegate decode="dng:decode" command="&quot;ufraw-batch&quot; --silent --create-id=also --out-type=png --out-depth=16 &quot;--output=%u.png&quot; &quot;%i&quot;"/>

This is how the error presented (not the quote in the path for /tmp):

** Message: 19:53:50.254: Error in canonicalize_file_name('/tmp): No such file or directory

display-im6.q16: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 --output='%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1966.

Chris

**Comment by dlemstra** [comment]
The current version of ImageMagick uses the version that works for you? I would advise you to upgrade.
