### ISSUE TITLE
Assertion _cairo_status_is_error (status) failed.

### ISSUE THREAD

**Issue by 7mioda** [ImageMagick/ImageMagick6#277]
### ImageMagick version

6.9.10-97

### Operating system

Linux

### Operating system, version and so on

amazon/aws-lambda-nodejs:18

### Description

Error: ```node: cairo-error.c:68: _cairo_error: Assertion `_cairo_status_is_error (status)' failed.```

I have included ImageMagick as one of the dependencies in my Lambda Docker container to convert PDF pages into images. 
This error occurs randomly, meaning that the same PDF may generate an error, but not consistently.

### Steps to Reproduce

- Docker container
```
FROM amazon/aws-lambda-nodejs:18

RUN yum -y update && \
    yum install -y \
        python3 \
        glib2-devel \
        libpng-devel \
        libjpeg-turbo-devel \
        giflib-devel \
        librsvg2-devel \
        libtiff-devel \
        libexif-devel \
        lcms2-devel \
        ImageMagick-devel \
        OpenEXR-devel \
        libgsf-devel \
        libxml2-devel \
        poppler-glib-devel \
        make \
        gcc \
        gcc-c++ \
        tar \
        curl

RUN cd /var/task && \
    curl -L https://github.com/libvips/libvips/releases/download/v8.13.3/vips-8.13.3.tar.gz | tar xz && \
    cd vips-8.13.3 && \
    ./configure --prefix=/var/task --with-pdfium --without-python && \
    make && \
    make install
```

- For the pdf you can use any pdf of your choice.

**Comment by dlemstra** [comment]
This looks like a libvips issue? And you are not explaining what we should do to reproduce this issue?

**Comment by 7mioda** [comment]
> This looks like a libvips issue? And you are not explaining what we should do to reproduce this issue?

This error occurs randomly the same PDF may generate an error, but not alla the time
