### ISSUE TITLE
Fail to build: test fail timeout

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick6#278]
### ImageMagick version

6.9.12.98

### Operating system

Linux

### Operating system, version and so on

debian

### Description

Fail to test:

See
https://salsa.debian.org/debian/imagemagick/-/jobs/4792544

### Steps to Reproduce

make check

### Images

none

**Comment by bastien-roucaries** [comment]
@dlemstra if you could get a glimpse and release a new version it will be perfect. This is needed on debian side

**Comment by urban-warrior** [comment]
Can we assume you are setting SOURCE_DATE_EPOCH?  If you run the unit tests without setting SOURCE_DATE_EPOCH, does that work?  If not, check the Time for `convert -list resource` and `convert -list policy`.  What is the time setting?

**Comment by bastien-roucaries** [comment]
it work without the SOURCE_DATE_EPOCH 

But it fail latter using a perfectly legal construct (using convert and SOURCE_DATE_EPOCH) 
https://salsa.debian.org/debian/imagemagick/-/jobs/4796266

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce the issue and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow. 

Once you confirm the patch, we'll push out a release with the patch.
