### ISSUE TITLE
Bug: PSD alpha sometimes incorrect

### ISSUE THREAD

**Issue by jonsneyers** [ImageMagick/ImageMagick6#28]
For PSD files with just a single layer, there are cases where the layer does have an alpha channel but the image itself should be considered to not have an alpha channel. Photoshop and GIMP correctly load these images as being fully opaque, but ImageMagick (incorrectly) uses the alpha channel from the layer data.

**Comment by dlemstra** [comment]
Thanks for pointing this out. We removed the incorrect detection of the alpha channel.
