### ISSUE TITLE
ImageMagick requires libtiff 4.0.3+ since 6.9.12-19

### ISSUE THREAD

**Issue by nradchenko** [ImageMagick/ImageMagick6#289]
### ImageMagick version

6.9.12-19

### Operating system

Linux

### Operating system, version and so on

Ubuntu 12.04

### Description

After commit f4feb3e, libtiff version 4.0.3 and onward is required (see [changelog entry](https://gitlab.com/libtiff/libtiff/-/blob/master/ChangeLog#L10018)).

```
coders/tiff.c: In function 'TIFFSetProfiles':
coders/tiff.c:2930:11: error: unknown type name 'TIFFField'
coders/tiff.c:2942:14: warning: assignment from incompatible pointer type [enabled by default]
coders/tiff.c:2943:9: warning: implicit declaration of function 'TIFFFieldDataType' [-Wimplicit-function-declaration]
coders/tiff.c: In function 'TIFFIgnoreTags':
coders/tiff.c:2158:5: warning: ignoring return value of 'strtol', declared with attribute warn_unused_result [-Wunused-result]
make[1]: *** [coders/magick_libMagickCore_6_Q16_la-tiff.lo] Error 1
make[1]: Leaving directory `/build/tmp-build/6.9.12-19/ImageMagick6-6.9.12-19'
make: *** [all] Error 2
```

My suggestion is to fix configure scripts to require a recent version of libtiff.

Maintaining a backward compatibility is also welcome, in case if legacy ImageMagick version is targeted for legacy systems :smile: 

### Steps to Reproduce

Try to build ImageMagick 6.9.12-19 for an older system, mine is Ubuntu 12.04 with libtiff 3.9.5.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
