### ISSUE TITLE
6.9.12-98: Tests are mass failing

### ISSUE THREAD

**Issue by Lastique** [ImageMagick/ImageMagick6#291]
### ImageMagick version

6.9.12-98

### Operating system

Linux

### Operating system, version and so on

Kubuntu 22.04

### Description

Running tests after ImageMagick 6.9.12-98 build shows most tests are failing. In most cases the error message is "time limit exceeded". There are also "no decode delegate for this image format", but those may be the consequence of the time limit error.

Here's a build log with tests output:
[build_log.txt](https://github.com/ImageMagick/ImageMagick6/files/13560255/build_log.txt)

### Steps to Reproduce

Build ImageMagick and run its tests.

**Comment by urban-warrior** [comment]
We have a fix for the issue in the 6.9.13-1, scheduled for release within the next few days.
