### ISSUE TITLE
Mogrify fails when converting a folder in NAS

### ISSUE THREAD

**Issue by cardcraft** [ImageMagick/ImageMagick6#299]
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

Kde neon 22.04 on kernal 5.19.0-50-generic (64-bit)

### Description

Whenever I use mogrify on my NAS it returns this error:

`mogrify: ../../magick/exception.c:1121: ThrowMagickExceptionList: Assertion `exception != (ExceptionInfo *) NULL' failed.
Aborted
`

### Steps to Reproduce

Use this command: mogrify -format avif -quality 95% *.jpg

This happens with any image to any format. It does not happen on the same images locally

**Comment by urban-warrior** [comment]
Download the latest ImageMagick release, ImageMagick-6.9.13-4.  If the problem persists, let us know and we will investigate further.

**Comment by cardcraft** [comment]
Omg I am so stupid, It was a problem with my drive - It made my admin user read only for some reason 😭
