### ISSUE TITLE
fft + ift roundtrip fails to produce a similar output image

### ISSUE THREAD

**Issue by FrostBird347** [ImageMagick/ImageMagick6#302]
### ImageMagick version

6.9.11-60 Q16 x86_64 2021-01-25 (installed via macports)
Features: Cipher DPC Modules 
Delegates (built-in): bzlib djvu fftw fontconfig freetype gslib heic jbig jng jp2 jpeg lcms ltdl lzma openexr png ps raw tiff webp x xml zlib

### Operating system

MacOS

### Operating system, version and so on

10.14.6

### Description

running `-fft`/`+fft` and `-ift`/`+ift` outputs images that look almost nothing like the original.

### Steps to Reproduce

- run `convert [image] -fft -ift [image_output]`
- observe the massive differences between the input and output images

### Images

inputted example images:
![kodim23](https://github.com/ImageMagick/ImageMagick6/assets/39435218/0b443e55-356c-42b7-b6da-dd988f41ceb6)
![testcard_rgba](https://github.com/ImageMagick/ImageMagick6/assets/39435218/840ad6e0-b652-4d85-b917-f03fc568fbad)
![testcard](https://github.com/ImageMagick/ImageMagick6/assets/39435218/05533096-8fd4-43db-b956-4de94b848a8c)
![dice](https://github.com/ImageMagick/ImageMagick6/assets/39435218/816885c5-c2d5-403f-9447-73e25f0d0a40)

images above after being converted:
![kodim23_OUT](https://github.com/ImageMagick/ImageMagick6/assets/39435218/6d6bc2e7-0ea8-4f02-8e8c-f7a1d038d1ac)
![testcard_rgba_OUT](https://github.com/ImageMagick/ImageMagick6/assets/39435218/f46dfd7b-d3aa-4030-be19-49a8ddf9010d)
![testcard_OUT](https://github.com/ImageMagick/ImageMagick6/assets/39435218/d06e48fb-25c5-429b-acb4-5d45206471b2)
![dice_OUT](https://github.com/ImageMagick/ImageMagick6/assets/39435218/8f8fc2f2-a6d4-4736-b70a-e1036530f087)

**Comment by urban-warrior** [comment]
Download the latest ImageMagick release, ImageMagick-6.9.13-4. If the problem persists, let us know and we will investigate further.
