### ISSUE TITLE
Silent ABI break in 6.9.10-11 on i386

### ISSUE THREAD

**Issue by rbalint** [ImageMagick/ImageMagick6#31]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Commit https://github.com/ImageMagick/ImageMagick6/commit/94a86b3324bed28b4ed4a80ff0be05dc58c0023e changed sizeof(MagickDoubleType) on i386 and made the low level ABI break for programs accessing some public structs via pointers.

### Steps to Reproduce

```
test.c:
#include <magick/MagickCore.h>
#include <stddef.h>
int main(){
printf("%d %d\n", offsetof(DrawInfo, text), sizeof(MagickDoubleType));
return 0;
}

# compiled with 6.9.10-8
$ ./a.out
280 12

# compiled with 6.9.10-14
$ ./a.out
272 8

```

### System Configuration

- ImageMagick version: 6.9.10-14
- Environment (Operating system, version and so on): Ubuntu 19.04 i386

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
