### ISSUE TITLE
Does ImageMagick 6 require C++11 now?

### ISSUE THREAD

**Issue by ryandesign** [ImageMagick/ImageMagick6#319]
### ImageMagick version

6.9.13-7

### Operating system

MacOS

### Operating system, version and so on

10.6

### Description

After [ImageMagick in MacPorts](https://ports.macports.org/port/ImageMagick) was updated to 6.9.13-7, a user reported that it did not build on old systems that don't have a C++11 compiler:

```
Magick++/lib/Color.cpp:226: error: 'nullptr' was not declared in this scope
```

This surprised me because I thought ImageMagick 6 was in maintenance mode and I did not expect a new requirement on C++11 to be introduced when we have been able to build ImageMagick 6 without a C++11 compiler for so many years.

This use of the C++11 feature `nullptr` was added in 037165b0f2965da2e7da240c031d13b0041dfed5 and is the only use of `nullptr` I can find in the ImageMagick 6 or 7 codebases. This was backported from ImageMagick/ImageMagick#7068.

### Steps to Reproduce

Build ImageMagick with a compiler that does not support C++11, such as Apple g++ 4.2.1 included in Xcode 3.2.6 for Mac OS X 10.6.

**Comment by dlemstra** [comment]
We have changed the statement in both IM6 and IM7.
