### ISSUE TITLE
Orientation info from HEIC decoder does not match actual pixel orientation

### ISSUE THREAD

**Issue by liuzhe0223** [ImageMagick/ImageMagick6#32]
Description & Steps to Reproduce
-----------------------------------

Same as https://github.com/ImageMagick/ImageMagick/issues/1232

System Configuration
-----------------------
- ImageMagick version: 6.9.10-20 Q16 x86_64
- Environment: Ubuntu 14.04.5 LTS 

I found this issue had been resolved by https://github.com/ImageMagick/ImageMagick/pull/1233 in ImageMagick7

**Comment by dlemstra** [comment]
Thanks for reporting this and we have fixed the orientation. We did not add the `heic:preserve-orientation` option to IM6. This will be an IM7 only feature.
