### ISSUE TITLE
ConvertImageCommand() function prints some geometry strings to stdout unexpectedly

### ISSUE THREAD

**Issue by teerapap** [ImageMagick/ImageMagick6#322]
### ImageMagick version

6.9.11.60

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04 (WSL2) (libmagickwand-dev 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3)

### Description

I'm using [GoMagick](https://github.com/gographics/imagick) (Go bindings of MagickWand C APIs)

My code calls function `ConvertImageCommand(....)` in a loop for a couple of times to find trim box of some images, it prints some geometry strings unexpectedly to stdout. 

I raised the issue gographics/imagick#318 to [GoMagick](https://github.com/gographics/imagick) and the maintainer thinks that it is the bug in the C APIs.
He tried with ImageMagick7 and encounters the problem as well.

I use this `ConvertImageCommand(....)` function because I cannot find the equivalent MagickWand C API to calculate the trim box (need both offset and size). 
Please let me know if there is another way to do this.  

Thanks

### Steps to Reproduce

This is the code that I can reproduce the problem.
```Go
    for i := 0; i < 100; i++ {
        ret, err := imagick.ConvertImageCommand([]string{
            "convert",
            "logo:",
            "-bordercolor", "white", // guiding border so that it trims only specified background color
            "-border", "1",
            "-fuzz", "10%",
            "-format", "%@",
            "info:",
        })
        if err != nil {
            return fmt.Errorf("finding trim box: %w", err)
        }
        ret.Info.Destroy()
    }
```

Around the 70th to 80th round, it will print below strings to stdout (or stderr I'm not sure).

```
457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x472+93+1457x  
```

**Comment by dlemstra** [comment]
This happens when there are multiple frames in the image:

```
magick ( logo: logo: ) -bordercolor white -border 1 -fuzz 10% -format %@ info:
457x472+93+1457x472+93+1
```

**Comment by teerapap** [comment]
@dlemstra I don't think it is the case.  My example code use single `logo:` so it should be a single frame image.

However, I just try to reproduce the problem with the C code below.

### Example code in C

```c
void main() {
        MagickWandGenesis();

        for (int i=0;i<100;i++) {

            printf("Round %d\n", i);

            char *cmd[] = {
                "convert",
                "logo:",
                "-bordercolor", "white",
                "-border", "1",
                "-fuzz", "10%",
                "-format", "%@",
                "info:"
            };

            ImageInfo *info = AcquireImageInfo();
            ExceptionInfo *exc = AcquireExceptionInfo();

            char *output = NULL;
            MagickBooleanType success = ConvertImageCommand(info, 11, cmd, &output, exc);
            DestroyImageInfo(info);
            DestroyExceptionInfo(exc);

            if (success == MagickFalse) {
                printf("Error at round %d\n", i);
                return;
            }
            printf("Output: %s\n", output);
        }

        MagickWandTerminus();
}
```
### Result

```
Round 0
457x472+93+1Output: 457x472+93+1
Round 1
457x472+93+1Output: 457x472+93+1
Round 2
457x472+93+1Output: 457x472+93+1
Round 3
457x472+93+1Output: 457x472+93+1
Round 4
457x472+93+1Output: 457x472+93+1
Round 5
457x472+93+1Output: 457x472+93+1
Round 6
457x472+93+1Output: 457x472+93+1
Round 7
457x472+93+1Output: 457x472+93+1
.....
```

I found that if I use the `info:` as the last argument, it will print the result (`457x472+93+1`) to stdout in addition to setting the result to `output` variable.    **Is this expected behavior?**

If this is expected, then I'll close the issue.

The problem goes back to the Go binding library that it probably buffers this *unexpected* stdout output somewhere and flush them to stdout at certain time.  Not immediately like C version.

If I use the `null:` as the last argument, it won't print the result to stdout and only setting the result to `output` variable which is what I want.

**Comment by dlemstra** [comment]
Your observation is correct. And using `null:` instead of `info:` prevents printing to stdout.
