### ISSUE TITLE
convert produces unwanted files when selected frame is out of bounds

### ISSUE THREAD

**Issue by pelallemant** [ImageMagick/ImageMagick6#332]
### ImageMagick version

6.9.11-60 and 6.9.12-98

### Operating system

Linux

### Operating system, version and so on

ubuntu 22.04 and 24.04

### Description

I'm using the command `convert -thumbnail 50x50 input.gif[$FRAME] thumbnail.png` to create a thumbnail of the desired $FRAME.

When $FRAME >= (count of frames of the .gif file), an error is displayed, the process exits with code 1, but the files thumbnail-0.png and thumbnail-1.png are created (if the animated gif has only 2 frames).

What I would expect is that no file should be produced since the frame is out of bounds.

The error is `convert-im6.q16: invalid image index 'input.gif' @ error/list.c/CloneImages/296`.

Note: It seems that that behaviour is fixed between 6.9.12-98 and 6.9.13.13, which is not available yet on ubuntu 24.04 apt repositories yet.

### Steps to Reproduce

- create a test folder with a src folder
- put several .jpg files in test/src 
- run `convert src/*.jpg -loop 0 -set delay 100 input.gif` to create an animated .gif
- run `convert input.gif[0] frame0.png`=> this exports the first image as expected
- run `convert input.gif[10] frame.png` => if your gif is < 10 frames, then this creates frame-0.png, frame-1.png, frame-2.png, frame-3.png, frame-4.png etc...

UPDATE

### Images

![screenshot](https://github.com/user-attachments/assets/96fd9cce-9054-4e11-af6f-20afe8907cdf)

For the images to create the .gif I picked 3 random images on https://www.pexels.com , the bug doesn't depend on these files, only the count of files in the .gif matters.

UPDATE 2

Here is the images/ folder: 
[images.zip](https://github.com/user-attachments/files/16509942/images.zip)

### SCRIPT

```
#!/bin/bash -e

# create a gif
convert images/*.jpg -loop 0 -set delay 100 input.gif

# this generates several files
convert input.gif[10] output/frame0.png

```

**Comment by dlemstra** [comment]
> Images
>
> Please upload images that can be used to reproduce issues in the area below. If the file type is not supported the file can be zipped and then uploaded instead.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
