### ISSUE TITLE
Converting .tif files result in distorted image

### ISSUE THREAD

**Issue by wbukiewicz** [ImageMagick/ImageMagick6#333]
### ImageMagick version

6.9.13-13

### Operating system

Linux

### Operating system, version and so on

Centos 7

### Description

After update from 6.9.12-24 to 6.9.13-13 converting .tif files result in distorted image.
Distorted image:
![result](https://github.com/user-attachments/assets/6add4a0f-328e-46c8-88e2-f3af70d839e5)

### Steps to Reproduce

If you use the image original.tif from the images.zip attachment, the conversion error should occur.
`convert -verbose   original.tif[0]    result.png`

> original.tif[0]=>original.tif TIFF 500x500 500x500+0+0 8-bit TrueColor sRGB 1.19234MiB 0.000u 0:00.005
original.tif[0]=>result.png TIFF 500x500 500x500+0+0 8-bit sRGB 338041B 0.180u 0:00.174

### Images

[images.zip](https://github.com/user-attachments/files/16362215/images.zip)

**Comment by dlemstra** [comment]
Cannot be reproduced in IM7 but is broken in IM6. We are probably missing a patch, investigating this now.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Comment by dlemstra** [comment]
I reverted this patch for now to give us some time to think about a better solution for this. So it might take a while longer before you will get this patch.

**Comment by dlemstra** [comment]
We made some new patches and with the next release you will get the correct output image.
