### ISSUE TITLE
Google ADs in documentation

### ISSUE THREAD

**Issue by Lastique** [ImageMagick/ImageMagick6#342]
### ImageMagick version

6.9.13-17

### Operating system

Linux

### Operating system, version and so on

N/A

### Description

Local HTML documentation contains references to Google ADs and counters. For example:

https://github.com/ImageMagick/ImageMagick6/blob/a61d721e3633724692590455a01fe76eff13b229/www/search.html#L36-L37

References like these are present in all html files.

Please remove these references as these can pose a privacy breach. Local documentation should not use references to external resources to be viewable on the local machine.

### Steps to Reproduce

1. Download ImageMagick 6.9.13-17.
2. Look into html files.

### Images

N/A.

**Comment by urban-warrior** [comment]
We have a script that removes the ads but the link changed so it failed on that step.  We will fix the script and update the docs so ads do not show.
