### ISSUE TITLE
Tables get distorted

### ISSUE THREAD

**Issue by lalitap25** [ImageMagick/ImageMagick6#344]
### ImageMagick version

7.1.1

### Operating system

Windows

### Operating system, version and so on

Windows server 2019

### Description

We are using imagemagick to convert some windows meta files(.wmf) to .png files and it works well with all kind of images except formulas and tables.

the values in table column gets [overlapped.]([Images.zip](https://github.com/user-attachments/files/17381478/Images.zip))

The zip file contains the original file and the converted file.

### Steps to Reproduce

unzip the attachment 
try to run this command
magick.exe -density 600 C:\visualization\magick-tmp\picture6627189417406342295.wmf -adaptive-resize 785 -gamma 0.9 C:\visualization\magick-tmp\picture6627189417406342295try10.png

### Images

NA

**Comment by dlemstra** [comment]
Closing this because you are creating way to many issues and discussions with the same questions.
