### ISSUE TITLE
Latest 6.9.13-19 Redhat version unavailable for download

### ISSUE THREAD

**Issue by scottbuscemi** [ImageMagick/ImageMagick6#353]
### ImageMagick version

6.9.13-19

### Operating system

Linux

### Operating system, version and so on

x86_64 RPM

### Description

The CentOS/x86_64 rpm is still showing 6.9.13-17 here: https://download.imagemagick.org/archive/linux/CentOS/x86_64/

As a result, the 6.9.13-19.x86_64.rpm link here is 404'ing: https://legacy.imagemagick.org/script/download.php#linux

### Steps to Reproduce

Go to https://legacy.imagemagick.org/script/download.php#linux and attempt to download the -19 rpm

### Images

<img width="966" alt="Screenshot 2024-12-02 at 2 54 45 PM" src="https://github.com/user-attachments/assets/0a4074f7-42d5-4c58-ac66-5f01df07076b">

**Comment by urban-warrior** [comment]
Thanks for bringing this issue to our attention.  The package files will be available later today.
