### ISSUE TITLE
SketchImage() causes memory leak

### ISSUE THREAD

**Issue by Watson1978** [ImageMagick/ImageMagick6#36]
`SketchImage()` API has totally same two line.

<img width="779" alt="_2019-02-20_23_22_12" src="https://user-images.githubusercontent.com/199156/53102702-96411380-356f-11e9-8401-9ab14cd2e02c.png">

https://github.com/ImageMagick/ImageMagick6/blob/48f354c142ab3985b8113e9ea96625c5fbc1a422/magick/fx.c#L4572

https://github.com/ImageMagick/ImageMagick6/blob/48f354c142ab3985b8113e9ea96625c5fbc1a422/magick/fx.c#L4577

The memory leak has been caused by redundant `AcquireAuthenticCacheView()` calling.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by Watson1978** [comment]
I confirmed this problem fixed with ImageMagick-6.9.10-35. thanks
