### ISSUE TITLE
[6.9.10-35] failed tests

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick6#37]
Same as https://github.com/ImageMagick/ImageMagick/issues/1529

```
FAIL: tests/validate-formats-memory.tap 1
FAIL: tests/validate-formats-disk.tap 1
FAIL: tests/validate-formats-map.tap 1
```

6.9.10-34 was OK.

Probably related to c01d8b02f3fa912a320ddad07a03212822f267ec

**Comment by urban-warrior** [comment]
Does the test pass with the latest release, 6.8.10-38?

**Comment by remicollet** [comment]
Yes everything is OK since 6.8.10-37 (I will try to build 6.8.10-38 later today)
