### ISSUE TITLE
Error reading pdf/pam files when the background is set to transparent

### ISSUE THREAD

**Issue by guyshapiro** [ImageMagick/ImageMagick6#38]
When reading a CMYK pdf file with python-wand, the following error is thrown:
```
wand.exceptions.CorruptImageError: unable to read image data `...' @ error/pnm.c/ReadPNMImage/1346
````
This issue was described on [1], [2], [3] and [4].
[1] https://imagemagick.org/discourse-server/viewtopic.php?f=6&t=35326&p=163174
[2] https://stackoverflow.com/q/50723020
[3] https://stackoverflow.com/q/52049129
[4] https://stackoverflow.com/q/54756773

In the case of CMYK pdf files, ImageMagick uses GS to convert the image to the
PAM format, by using the '-sDEVICE=pamcmyk32' argument.
I've extracted the intermediate PAM files produced by GS. Those files can be
converted by the ImageMagick command line utilities, but opening them with
python-wand produced the same error.
Such PAM image file is attached [here](https://github.com/ImageMagick/ImageMagick6/files/3003682/cmyk.zip).
This short python snippet can be used to reproduce the error:
```python
import wand.image
wand.image.Image(filename="/path/to/cmyk.pam")
```

Digging into the python-wand code, I found that the following code [5] is related to
the issue:
```python
with Color('transparent') as bg:  # FIXME: parameterize this
    result = library.MagickSetBackgroundColor(self.wand,
                                              bg.resource)
```
[5] https://github.com/emcconville/wand/blob/master/wand/image.py#L4996

Changing the background color to 'white' or commenting-out those lines made
the error go away.

Looking at the reader code on "coders/pnm.c", I believe that I found the root
cause of the issue. This code takes the transparent background color as an
indication that the image file contains an alpha channel.

In line 450, SetImageBackgroundColor is called. It sets image->matte based on
the background color transparency.
Then, in line 970, the number of expected channels on the file is
increased based on image->matte.
So, setting the background color to transparent made the reader expect an
alpha channel in the input image, although the headers of the image tell that
it doesn't include such a channel.

As a result, the reader expects more data bytes than the file has, leading to
the described exception.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
