### ISSUE TITLE
[6.9.10.37] failed tests on FreeBSD

### ISSUE THREAD

**Issue by kwm81** [ImageMagick/ImageMagick6#39]
Btw how do the test find fonts? I'm building with both fontconfig and freetype enabled and the test suite can't find the helvetica font. and I have several hiits for "Helvetica" when I run the fc-list command.

==========================================
   ImageMagick 6.9.10: ./test-suite.log
==========================================

# TOTAL: 76
# PASS:  70
# SKIP:  0
# XFAIL: 0
# FAIL:  6
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/wandtest
====================

tests/wandtest.c main 5323 non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4348
1..1
Reading images...
Iterate forward...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Iterate reverse...
index 4 scene 4
index 3 scene 3
index 2 scene 2
index 1 scene 1
index 0 scene 0
Remove scene 1...
index 0 scene 0
index 1 scene 2
index 2 scene 3
index 3 scene 4
Insert scene 1 back in sequence...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Set scene 2 to scene 1...
index 0 scene 0
index 1 scene 1
index 2 scene 1
index 3 scene 3
index 4 scene 4
Apply image processing options...
not ok
FAIL: tests/wandtest.tap 1

FAIL: Magick++/demo/demos
=========================

1..24
File: /usr/home/kwm/sources/freebsd/ports/graphics/ImageMagick6/work/ImageMagick-6.9.10-37/Magick++/demo//model.miff
  TopLeftColor     = 
  TopRightColor    = 
  BottomLeftColor  = 
  BottomRightColor = 
  filter:brightness:mean = 31077.3
  filter:brightness:standard-deviation = 14635.5
  filter:brightness:kurtosis = 0.657217
  filter:brightness:skewness = 1.34114
  filter:saturation:mean = 14031.6
  filter:saturation:standard-deviation = 8379.05
  filter:saturation:kurtosis = 0.631727
  filter:saturation:skewness = 1.03422
ok
PASS: Magick++/demo/demos.tap 1
Caught exception: button: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1333
not ok
FAIL: Magick++/demo/demos.tap 2
Read images ...
Creating thumbnails...
  add noise ...
  add noise (blue) ...
  annotate ...
Caught exception: demo: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1333
not ok
FAIL: Magick++/demo/demos.tap 3
Writing image "flip_out.miff" ...
ok
PASS: Magick++/demo/demos.tap 4
angle 0
Caught exception: gravity: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1333
not ok
FAIL: Magick++/demo/demos.tap 5
Caught exception: piddle: non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4348
not ok
FAIL: Magick++/demo/demos.tap 6
Caught exception: shapes: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1333
not ok
FAIL: Magick++/demo/demos.tap 7
ok
PASS: Magick++/demo/demos.tap 8
ok
PASS: Magick++/demo/demos.tap 9
ok
PASS: Magick++/demo/demos.tap 10
ok
PASS: Magick++/demo/demos.tap 11
ok
PASS: Magick++/demo/demos.tap 12
ok
PASS: Magick++/demo/demos.tap 13
ok
PASS: Magick++/demo/demos.tap 14
ok
PASS: Magick++/demo/demos.tap 15
ok
PASS: Magick++/demo/demos.tap 16
ok
PASS: Magick++/demo/demos.tap 17
ok
PASS: Magick++/demo/demos.tap 18
ok
PASS: Magick++/demo/demos.tap 19
ok
PASS: Magick++/demo/demos.tap 20
ok
PASS: Magick++/demo/demos.tap 21
ok
PASS: Magick++/demo/demos.tap 22
ok
PASS: Magick++/demo/demos.tap 23
ok
PASS: Magick++/demo/demos.tap 24

**Comment by urban-warrior** [comment]
All the unit tests passed for us on FreeBSD 12.0. We first installed the ImageMagick6 package (pkg install) which downloaded and installed all the ImageMagick dependencies. New we configured and build ImageMagick from source. Finally we ran the unit tests and they all passed without complaint.

**Comment by urban-warrior** [comment]
Forgot to mention, you'll also need the gsfonts package to expose the Helvetica font (e.g. pkg install gsfonts).

**Comment by kwm81** [comment]
With 6.0.10.39 and after installing gsfonts, all test pass.

**Comment by jeroen** [comment]
Also seeing this error on Ubuntu Xenial using (a backport of) IM 6.9.10-23: https://travis-ci.org/ropensci/magick/builds/541493453

I think the error happens somewhere during drawing text (annotating). The error is raised on [this line](https://github.com/ImageMagick/ImageMagick6/blob/6.9.10-23/magick/draw.c#L4301) in imagemagick.
