### ISSUE TITLE
win7: Procedure starting point “_free_locale” not found in DLL “msvcrt.dll”

### ISSUE THREAD

**Issue by michalfapso** [ImageMagick/ImageMagick6#42]
On Windows 7, an application linked with libMagickCore-6.Q8-6.dll shows the following error:
Procedure starting point “_free_locale” not found in DLL “msvcrt.dll”

The application and libMagickCore were compiled on Windows 10 in Msys2 with both mingw64 and mingw32. The problem is, that the library imports "_free_locale" from "msvcrt.dll", but on Windows 7, the import is missing.

It seems that the issue was caused by the commit 75c562aa08f31a7e4a6128bcaad030cee1db9596 which calls freelocale(), which is translated to _free_locale by the preprocessor:
https://github.com/ImageMagick/ImageMagick6/blob/e2a21735e3a3f3930bd431585ec36334c4c2eb77/magick/nt-base.h#L105

Our workaround was to change this line:
https://github.com/ImageMagick/ImageMagick6/blob/e2a21735e3a3f3930bd431585ec36334c4c2eb77/magick/locale.c#L65
to:
```c++
#if (defined(MAGICKCORE_HAVE_NEWLOCALE) || defined(MAGICKCORE_WINDOWS_SUPPORT)) && !defined(__MINGW32__)
```
which disables `MAGICKCORE_LOCALE_SUPPORT`

GCC version: g++.exe (Rev1, Built by MSYS2 project) 7.3.0
msys2 package name: mingw64/mingw-w64-x86_64-gcc 7.3.0-1

Thanks for your hard work,
Michal

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
