### ISSUE TITLE
Metadata in PGM file not being preserved

### ISSUE THREAD

**Issue by dchaddock** [ImageMagick/ImageMagick6#48]
### Description
When running "convert" on a PGM file with metadata between the magic number and dimension/bitdepth lines, any new line characters are removed. This behaviour started at 7.0.8-x from what I can tell. All prior versions that I have worked with have preserved the new line characters (7.0.7, 6.x).

Head of file before running convert:
<pre>$ head -n 6 white.pgm 
P5
# metadata line 1
# metadata line 2
# metadata line 3
100 100
65535</pre>

Head of file after running convert:
<pre>$ head -n 4 new.pgm 
P5
# metadata line 1 metadata line 2 metadata line 3
100 100
65535</pre>

Refer to ImageMagick V7 issue previously addressed. Looks like this issue was propagated to v6. https://github.com/ImageMagick/ImageMagick/issues/1425

### Steps to Reproduce
1. Create a blank PGM file
`convert -size 100x100 xc:white white.pgm`
2. Insert metadata into file
`sed -i -e '/^P5/s/P5/P5\n# metadata line 1\n# metadata line 2\n# metadata line 3/g' white.pgm`
3. Run convert (note, I realize that running convert on this image actually doesn't accomplish anything, but, it's the most basic example)
`convert white.pgm new.pgm`

### System Configuration
- CentOS 7, x64, kernel version, kernel 3.10.0-862.14.4.el7.x86_64
- Behaviour occurs on ImageMagick 6.7.8-9

**Comment by urban-warrior** [comment]
We are getting expected results for the latest releases of IMv6 and IMv7.  Perhaps the bug you reported was transient.  If you can reproduce the problem with the latest releases of ImageMagick, let us know.

**Comment by dchaddock** [comment]
Ah, I see that the latest version of ImageMagick in the CentOS 7 EPEL repo isn't the latest. Not surprising since they lag quite a bit. 

How do I install the latest 6.x version? Is it only possible to do by building from source?

Thanks!

**Comment by urban-warrior** [comment]
Build from source or download the RPM @ https://legacy.imagemagick.org/script/download.php#unix.
