### ISSUE TITLE
heic.c build failure

### ISSUE THREAD

**Issue by antonio-rojas** [ImageMagick/ImageMagick6#50]
coders/heic.c: In function ‘ReadHEICImage’:
coders/heic.c:345:7: error: too many arguments to function ‘IsHeifSuccess’
  345 |   if (IsHeifSuccess(&error,image,exception) == MagickFalse)
      |       ^~~~~~~~~~~~~
coders/heic.c:117:26: note: declared here
  117 | static MagickBooleanType IsHeifSuccess(struct heif_error *error, Image *image)
      |                          ^~~~~~~~~~~~~
make[1]: *** [Makefile:8235: coders/heic_la-heic.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/imagemagick6/src/ImageMagick-6.9.10-52'
make: *** [Makefile:5681: all] Error 2

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
