### ISSUE TITLE
unable to parse expression `random()' @ error/fx.c/FxGetSymbol/1886

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick6#51]
I upgraded from 6.9.10-50 to 6.9.10-53 and now get this error: 

    unable to parse expression `random()' @ error/fx.c/FxGetSymbol/1886

When calling `Image.fx(std::string("random()"))` .

**Comment by dlemstra** [comment]
The correct value is `rand()` instead of `random()`. We recently fixed a bug in the FX parser and that is why you are now seeing this.

**Comment by jeroen** [comment]
OK thanks!
