### ISSUE TITLE
SVG conversion regression(?)

### ISSUE THREAD

**Issue by PRR24** [ImageMagick/ImageMagick6#54]
```convert file.svg -auto-orient -resize 28x28 -size 28x28 xc:white +swap -gravity center -composite file.png```
results correct png using ImageMagick 6.8.9-9 Q16 x86_64 2019-06-15 (Ubuntu 16.04)
but invalid image using ImageMagick 6.9.7-4 Q16 x86_64 20170114 (Ubuntu 18.04)
During conversion latter displays:
```convert-im6.q16: unrecognized color `_Linear1' @ warning/color.c/GetColorCompliance/1052.
convert-im6.q16: unable to open image `_Linear1': No such file or directory @ error/blob.c/OpenBlob/2701.
convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.```

SVG file has internally
```
<path style="fill:url(#_Linear1);fill-rule:nonzero;" ...
<linearGradient id="_Linear1" ...
```

BTW, the 20170114 in version number under Ubuntu 18.04 looks bit weird compared to 2019-06-15 on Ubuntu 16.04

Thanks in advance.

**Comment by PRR24** [comment]
Turns out nothing to do with IM, Ubuntu 18.04 distributes IM without rsvg delegate.

**Comment by dlemstra** [comment]
Thanks for coming back to report this.
