### ISSUE TITLE
SVG to PNG

### ISSUE THREAD

**Issue by lukegradtouch** [ImageMagick/ImageMagick6#55]
Hi, just recently we've noticed an inability to convert from SVG to PNG.

the error in the php-fpm logs we have is `magick/blob.c:1252: WriteBlobStream: Assertion `image->blob->type != UndefinedStream' failed.`

we use with php-pecl-imagick and centos 7.6, version 6.9.10.62-1.el7.remi appears to have the issue whilst version 6.9.10.59-1.el7.remi appears to work

We've tried to roll back but repositories no longer list the packages despite them being only 2 weeks old...

Thanks in advance for assistance.

**Comment by lukegradtouch** [comment]
Example PHP code that we're using:

```

        $image = new Imagick();
        $image->setFormat('svg');

        $image->setFont('font.ttf');
        $image->readImageBlob($svg);
        $image->setImageFormat("png");
        $blob = $image->getImageBlob();
```

**Comment by dlemstra** [comment]
This look like something that should be looked at by the maintainer(s) of `Imagick`. And if this is a problem in our code they can come back to us with some more information.
