### ISSUE TITLE
Convert crashing

### ISSUE THREAD

**Issue by PRR24** [ImageMagick/ImageMagick6#56]
Ubuntu 18.04
```
$ convert --version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```
Computer has inkscape installed.
```
$ convert file.png file2.png
convert: ../../magick/quantum.c:216: DestroyQuantumInfo: Assertion `quantum_info != (QuantumInfo *) NULL' failed.
Aborted (core dumped)
```
file.png itself: https://files.startupincluder.com/2019-08/kr0ri9gnnc2covqpl5vz6yvyqhjyk148101/1.Horizantal.png

Works without issues on Ubuntu 16.04 with ImageMagick 6.8.9-9 Q16 x86_64 2019-06-15

**Comment by urban-warrior** [comment]
ImageMagick version 6.9.7-4 is way old.  Our recommendation is to upgrade your release of ImageMagick

**Comment by PRR24** [comment]
Tracked the issue down to policy resource restrictions that are very restrictive on Ubuntu 18.04 by default. After adjustments, all tested files convert nicely.

While it is clear that IM should not crash in such situation, It's probably not feasible to spend any time on it for IM6. If I should encounter similar problem with IM7, I will open a separate issue for it.

**Comment by mindtonic** [comment]
@PRR24 How did you solve `Tracked the issue down to policy resource restrictions that are very restrictive on Ubuntu 18.04 by default. After adjustments, all tested files convert nicely.` I am using these same versions and have the same issues. Any leads on how to make the adjustments?

**Comment by PRR24** [comment]
/etc/ImageMagick-6/policy.xml

**Comment by subhosuper** [comment]
What are the adjustments that you made exactly? please let us know.
Facing the same issue

**Comment by mindtonic** [comment]
+1

**Comment by yoursunny** [comment]
> Tracked the issue down to policy resource restrictions that are very restrictive on Ubuntu 18.04 by default. After adjustments, all tested files convert nicely.
> /etc/ImageMagick-6/policy.xml

I'm trying to process a 1343x59305 image and am facing the same issue.
I changed three settings in `/etc/ImageMagick-6/policy.xml` and the file converted successfully:

```xml
  <policy domain="resource" name="width" value="64KP"/>
  <policy domain="resource" name="height" value="64KP"/>
  <policy domain="resource" name="disk" value="4GiB"/>
```

The old values were 16KP, 16KP, 1GiB.

**Comment by Demetrio92** [comment]
Issue closed. Can we have a more modern config by default? Or generate it depending on the config of the machine?..

**Comment by urban-warrior** [comment]
Not sure what you mean by more modem config.  See https://imagemagick.org/script/security-policy.php.  It details why each security policy is different not only based on the host attributes but also the user's local security policies making it difficult to create a one-size fits all policy.  Any user is welcome to contribute a security policy configuration script that asks the user a series of questions and outputs a security policy based on their answers.  If there is wide-adoption, we will consider adding it to the ImageMagick distriibution.
