### ISSUE TITLE
Converting 1-bpp PNG into TIFF does not preserve depth

### ISSUE THREAD

**Issue by ppisar** [ImageMagick/ImageMagick6#57]
See https://github.com/ImageMagick/ImageMagick/issues/277 for a description and a reproducer. 6.9.10-64 version is still broken.

**Comment by dlemstra** [comment]
There is no need to open an new issue.

**Comment by ppisar** [comment]
I don't have permissions to reopen the original one.

**Comment by ppisar** [comment]
6.9.10-67 is broken.
