### ISSUE TITLE
convert -size 1x1 xc:white white.pnm creates a black image

### ISSUE THREAD

**Issue by ppisar** [ImageMagick/ImageMagick6#58]
I found a regression in ImageMagick. After upgrading ImageMagick from 6.9.10.28 to 6.9.10.64 this command:

~~~~
convert -size 1x1 xc:white white.pnm
~~~~

creates a black PNM image. It used to be a white one.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by ppisar** [comment]
I confirm 6.9.10.67-1 fixed it, but at the same time it broke generating a black image:

~~~~
[test@fedora-32 tmp]$ convert xc:black black.pnm
[test@fedora-32 tmp]$ hexdump -C black.pnm 
00000000  50 34 0a 31 20 31 0a 00                           |P4.1 1..|
00000008
~~~~

**Comment by ppisar** [comment]
I tried 6.9.10-75 and it creates the both white and black correctly. So this issue can be closed.
