### ISSUE TITLE
 Please bump version when soname change #1150 

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick6#6]
Hi,

Soname have changed again (.5 => .6) in a patch version which is terribly hard to manage when we want to be able to install multiple version (ImageMagick6 package and default ImageMagick from the distro), especially because only version (6.9.9) is used for directory layout.

So, 6.9.10 will be better.

**Comment by urban-warrior** [comment]
We will bump the minor patch release after the next point release.
