### ISSUE TITLE
convert xc:black black.pnm creates a white image

### ISSUE THREAD

**Issue by pacien** [ImageMagick/ImageMagick6#60]
This issue follows https://github.com/ImageMagick/ImageMagick/issues/1636.

`convert xc:black black.pnm` generates an image containing a white pixel instead of a black one like it used to.

The issue has been fixed in imagemagick 7 (https://github.com/ImageMagick/ImageMagick/commit/a687199a1a3bbdad0c960fac5f1aa4e1ad1538ac) but the backport to imagemagick 6 (https://github.com/ImageMagick/ImageMagick6/commit/cfb643774a39d530bf1eb75bef3f505f96606927) doesn't seem to have solved the problem.

ImageMagick 6.9.10-69 is affected by this issue.
(ImageMagick 7.0.9-0 behaves as expected.)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pacien** [comment]
I confirm that d7e1580 solved the issue for `convert xc:black black.pnm` which now correctly generates a black image.

__However__ this seems to have broken `convert xc:white white.pnm` which now generates a black image too instead of a white one!

**Comment by pacien** [comment]
ImageMagick/ImageMagick6@cb55f13 and ImageMagick/ImageMagick@bd52c99 __solved__ the issue for ImageMagick 6 and 7 respectively, for both `xc:black` and `xc:white`. Thanks!
