### ISSUE TITLE
Any way to force input file mimetype ?

### ISSUE THREAD

**Issue by inkhey** [ImageMagick/ImageMagick6#64]
For technical reason, i do need to convert imagemagick file who don't have file_extension in their own filename but i do have mimetype of the file. Is there is anyway to force imagemagick to use mimetype provided to process the file instead of guessed one by imagemagick.

Use case is for raw file like .ARW(image/x-sony-arw), they are considered as tiff if no file_extension is provided, which raise this kind of issue:
```

 ❯ convert DSC08523 -layers merge test.jpg
convert-im6.q16: Unknown field with tag 50341 (0xc4a5) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
convert-im6.q16: TIFF directory is missing required "ImageLength" field. `MissingRequired' @ error/tiff.c/TIFFErrors/564.
convert-im6.q16: no images defined `test.jpg' @ error/convert.c/ConvertImageCommand/3258.
```

**Comment by urban-warrior** [comment]
Try this command instead:

`❯ convert arw:DSC08523 -layers merge test.jpg`
