### ISSUE TITLE
Compilation error in MacOS (do not support _aligned_alloc)

### ISSUE THREAD

**Issue by joonsung90** [ImageMagick/ImageMagick6#66]
Hi.
Recently, I have faced some compilation errors ("do not support _aligned_alloc") while building ImageMagick6 on my Mac.

I found the ImageMagick7 had suffered from a similar issue and the bug is fixed with this [commit 25b296e](https://github.com/ImageMagick/ImageMagick/commit/25b296e564af6e000b8aaf8809f940c6eb1d3515).
Could you apply this commit to ImageMagick@6?

Thanks.

**Comment by dlemstra** [comment]
That commit was already applied to ImageMagick 6: https://github.com/ImageMagick/ImageMagick6/commit/29344447a3053e46a686aaf01e6f30c4bc3e3875. Which version did you test this with?

**Comment by joonsung90** [comment]
Hi, I used ImageMagick6 (6.9.10-79) (earlier version than the commit you mentioned).
I found the new version of the released tar ball (6.9.10-80) which contains the commit.
Thanks.
