### ISSUE TITLE
[6.9.10-86] failed test on Manjaro

### ISSUE THREAD

**Issue by cengique** [ImageMagick/ImageMagick6#69]
I'm trying to compile a legacy ImageMagick6-git AUR package for Arch/Manjaro Linux and I copied and modified the [PKGBUILD](https://github.com/ImageMagick/ImageMagick6/files/4051810/PKGBUILD.txt) file of the 7.x version to try compile the 6.9 version. Everything compiles, but one test fails:

Magick++/tests/tests.log:
```
1..12
ok
PASS: Magick++/tests/tests.tap 1
Testing throwing and catching exceptions. A program crash or a message
that the exception was not caught indicates a test failure.  A properly
formatted exception message indicates success:
Caught exception, good!:
  "lt-attributes: unable to open image `foo': No such file or directory @ error/blob.c/OpenBlob/2881"
Line: 1300, signature (1bee74f71cd8a2054a49d04df3f8c099623b1f8eac2b66b7394ec329c42a15b9) is incorrect
1 failures
not ok
FAIL: Magick++/tests/tests.tap 2
ok
PASS: Magick++/tests/tests.tap 3
```

Any clues?

**Comment by urban-warrior** [comment]
Try the latest release of ImageMagick.  Do any of the unit tests fail?  They do pass for us in the 6 different environments we use to build the releases.
