### ISSUE TITLE
Failing to convert .fig files

### ISSUE THREAD

**Issue by mooninite** [ImageMagick/ImageMagick6#71]
Version: 6.9.10-86

Using the .fig file from
https://libvirt.org/git/?p=libvirt.git;a=tree;f=docs;h=7aae2bb533162e7c5f8a72e66358ee6019fe5e80;hb=HEAD
try to convert it:

$ convert -rotate 90 ../docs/libvirt-daemon-arch.fig /tmp/libvirt-daemon-arch.png

/usr/bin/mv: cannot stat '/tmp/magick-25797043oXOlQHfRVZk.svg': No such file or directory
convert: delegate failed `'uniconvertor' '%i' '%o.svg'; /usr/bin/mv '%o.svg' '%o'' @ error/delegate.c/InvokeDelegate/1958.
convert: unable to open file `/tmp/magick-2579704AXcjGo2e6VAk': No such file or directory @ error/constitute.c/ReadImage/605.
convert: no images defined `/tmp/libvirt-daemon-arch.png' @ error/convert.c/ConvertImageCommand/3226.

**Comment by urban-warrior** [comment]
ImageMagick leverages the uniconvertor utility to interpret FIG images.  Chances are the utility is not installed on your host or it is not working properly.

**Comment by rwmjones** [comment]
I should say that libvirt "solved" this by converting the FIG files to SVG: https://gitlab.com/libvirt/libvirt/-/commit/9ad637c9651ff29955dd6aa8fe31f639b42b7315

**Comment by mooninite** [comment]
Yeah, Fedora does not ship that utility. Thanks for the info.
