### ISSUE TITLE
Problems Converting FAX (G3) Images

### ISSUE THREAD

**Issue by gjmunro** [ImageMagick/ImageMagick6#74]
We are having issues processing FAX images doing something like:
convert fax.g3 -trim fax.png

I was able to get things working by incrementing the q variable in the section below.  Otherwise it seems only the first column of pixels is updated and I will get the following:
convert: geometry does not contain image `/tmp/PWBE15EGRR1200.g3' @ warning/attribute.c/GetImageBoundingBox/244

https://github.com/ImageMagick/ImageMagick6/blob/651cdce0aafa99a3e952e4d473390829765a118f/magick/compress.c#L624-L633

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
