### ISSUE TITLE
Build failing on CentOS6 with gcc-8 (devtoolset-8)

### ISSUE THREAD

**Issue by thebaptiste** [ImageMagick/ImageMagick6#75]
Hi
I'm trying to build ImageMagick6 on CentOS 6 with gcc 8 (using devtoolset-8). In this case, aligned_alloc is not defined in stdlib.h, we should use posix_memalign instead.

configure doesn't find aligned_alloc ==> HAVE__ALIGNED_MALLOC is not set to 1 in config/config.h

But , when building, we have this test in magick/magick-config.h : 
```
#if defined(__STDC_VERSION__) && __STDC_VERSION__ > 201112L && !defined(__MINGW32__)
# define MAGICKCORE_HAVE_STDC_ALIGNED_ALLOC 1
#endif
```

So MAGICKCORE_HAVE_STDC_ALIGNED_ALLOC is set to 1 (which is wrong in my case), so aligned_alloc is used in magick/memory.c and the build fails.
Could you do something about it ?

Regards

**Comment by thebaptiste** [comment]
I have not tried, but I think there is the same issue for ImageMagick7

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by thebaptiste** [comment]
Thanks for your reactivity.
Happy to have been able to contribute to ImageMagick improvment.
