### ISSUE TITLE
help me to find version ImageMagick 6.7.8-9 2019-08-08 Q16

### ISSUE THREAD

**Issue by xuanson97hg** [ImageMagick/ImageMagick6#76]
i can't file ImageMagick 6.7.8-9 2019-08-08 Q16 for macos

**Comment by urban-warrior** [comment]
Most older releases are available here: https://imagemagick.org/download/releases/.  You can find ImageMagick 6.7.8-9 with Google which return this location: https://launchpad.net/imagemagick/+milestone/6.7.8-9.
