### ISSUE TITLE
CentOS 7.8.2003 -- ImageMagick and ImageMagick6-libs conflict

### ISSUE THREAD

**Issue by dogaoz** [ImageMagick/ImageMagick6#81]
### Prerequisites

- [ ✅] I have written a descriptive issue title
- [ ✅] I have verified that I am using the latest version of ImageMagick
- [ ✅] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce

"yum update" on CentOS 7.7
```
Transaction check error:

file /usr/lib64/libMagickCore-6.Q16.so.6.0.0 from install of ImageMagick-6.9.10.68-3.el7.x86_64 conflicts with file from package ImageMagick6-libs-0:6.9.11.6-1.el7.remi.x86_64

file /usr/lib64/libMagickWand-6.Q16.so.6.0.0 from install of ImageMagick-6.9.10.68-3.el7.x86_64 conflicts with file from package ImageMagick6-libs-0:6.9.11.6-1.el7.remi.x86_64.
```
ImageMagick6-libs package conflicts with newer ImageMagick package.

### System Configuration

CentOS 7.7

- ImageMagick version:
- Environment (Operating system, version and so on): CentOS 7.7
- Additional information:

**Comment by remicollet** [comment]
This is NOT an ImageMagick bug, but a packaging issue.

Tracked, with fix instruction on https://github.com/remicollet/remirepo/issues/144
