### ISSUE TITLE
6.9.11-20 Broken build with old libtiff

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick6#84]
Since 218d6abc4e36596c90a07463bfb2ab9e8312efbb

```
coders/tiff.c: In function 'TIFFGetProfiles':
coders/tiff.c:642: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
coders/tiff.c:642: error: 'field' undeclared (first use in this function)
coders/tiff.c:642: error: (Each undeclared identifier is reported only once
coders/tiff.c:642: error: for each function it appears in.)
coders/tiff.c:647: warning: implicit declaration of function 'TIFFFieldDataType'
coders/tiff.c: In function 'TIFFIgnoreTags':
coders/tiff.c:2203: warning: ignoring return value of 'strtol', declared with attribute warn_unused_result
make[1]: *** [coders/tiff_la-tiff.lo] Error 1

```

**TIFFField** doesn"t exist with old libtiff

Affected: CentOS / RHEL 6 with libtif 3.9

**Comment by urban-warrior** [comment]
hanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by remicollet** [comment]
I confirm the fix,
Thanks
