### ISSUE TITLE
6.9.11-20 behavior change with DrawSetTextInterlineSpacing

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick6#85]
Writing a 3 lines with **MagickAnnotateImage**

With **6.9.11-19** version, setting **DrawSetTextInterlineSpacing** to 0:

![interline_spacing_test_0](https://user-images.githubusercontent.com/270445/85255941-8be4a180-b463-11ea-95c8-7f6cb5b05c75.png)

With **6.9.11-20**

![interline_spacing_test_0](https://user-images.githubusercontent.com/270445/85255969-969f3680-b463-11ea-9618-d49391ab868b.png)

Found in failing php extension test suite.

https://github.com/Imagick/imagick/blob/master/tests/279_ImagickDraw_setTextInterlineSpacing.phpt

Seems a regression

**Comment by Danack** [comment]
Perhaps I should discuss it as a separate issue, but setting up a github action to run the tests of libraries that use ImageMagick would make BC breaks like this easier to spot.

**Comment by remicollet** [comment]
@Danack I'm your bot;)

(I mean I build all IM versions... and rebuild imagick as part of my QA work)


But indeed, seems a good idea

**Comment by urban-warrior** [comment]
Agreed.  We're working on expanding the capabilities of actions as time permits.  We'll see if we can add CentOS 6 as an action.

**Comment by remicollet** [comment]
Same issue with 147e715 applied

**Comment by remicollet** [comment]
> We'll see if we can add CentOS 6 as an action.

This issue is not related to CentOS 6 ;)

**Comment by remicollet** [comment]
Looking at 77849ee5a5f0481e0bfd67f72f6b7e07c5d2ba46

Is a possible alternative fix to have some default value for interline_spacing (pointsize ?) ?
So wrapping will work and also forcing interline_spacing to 0 (no wrapping)

**Comment by remicollet** [comment]
See pr #86

**Comment by remicollet** [comment]
22 seems OK.
