### ISSUE TITLE
Caption without defining font size filling space horizontally but not vertically at times.

### ISSUE THREAD

**Issue by johnrb68** [ImageMagick/ImageMagick6#87]
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 

I have a script that uses ImaageMagick to place a always changing paragraph of text into a box size.
If the character length of the text is smaller then the know amount to fill the box at a know length (example 200 characters) then I define the font size. If it is larger and will overflow, then I do not define the font size to it will fit all the text in the box.

However sometimes instead of wrapping the text to several lines to fill the space, it will only use a few lines and really small text.
600x145 box with 26 point font if less than 200 characters in this example.
![Caption example IM6](https://user-images.githubusercontent.com/3821946/86625529-32b45c00-bf93-11ea-8765-6f6ade59399f.PNG)

There doesn't seem to be rhyme or reason as to why it does it with really small text like this. Some times it will fill all the space as expected, but then sometimes it scrunches it all up like in the image example. This happens with many different sized boxes as well, doing a similar thing where the text is tiny when there was plenty of space to make the text larger in the same space.

I can't seem to find any other setting or any other way to get it to not do this.

Any suggestions?

Is this a known bug that I could not find documented?

Thank you.

**Comment by dlemstra** [comment]
The version that you are using is ancient. Can you give it a try with the latest version?

**Comment by johnrb68** [comment]
That is the latest verified version that is in the Ubuntu Server 18.04 LTS Repositories.
I'll look into how to install the latest version on Ubuntu in the next few days.
