### ISSUE TITLE
Require errror

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick6#88]
https://github.com/ImageMagick/ImageMagick6/blob/4630cb0592f9f8f0dbfd448b3e8ca8659922d88d/Magick%2B%2B/lib/ImageMagick%2B%2B.pc.in#L11

is incorrect it  should use the same require than
https://github.com/ImageMagick/ImageMagick6/blob/4630cb0592f9f8f0dbfd448b3e8ca8659922d88d/Magick%2B%2B/lib/Magick%2B%2B.pc.in#L11

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
