### ISSUE TITLE
Top level index.html is a mess, bad links, possible duplicate of www/index.html

### ISSUE THREAD

**Issue by mooninite** [ImageMagick/ImageMagick6#89]
### Description
The /index.html file has bad links:
- "https://imagemagick.org/www/www/index.html"
- "www/www/download.html"
- etc.

It looks like someone did a search and replace to add www/ everywhere without looking at the output.

Why is there a top level index.html anyway? The 'www/index.html' file is nearly identical... but they are both slightly different.

**Comment by urban-warrior** [comment]
The authoritative ImageMagick version 6 website is https://legacy.imagemagick.org.   For ImageMagick 7, see https://imagemagick.org.  Those should be the only two links you need to review the capabilities of ImageMagick.

**Comment by mooninite** [comment]
I don't think you followed my bug report. This is not a report about the ImageMagick public website. The report is against the "index.html" file in this git repo.

https://github.com/ImageMagick/ImageMagick6/blob/master/index.html

**Comment by urban-warrior** [comment]
Got it now.  Notice your link in your original posting does not mention Github, but instead points to the ImageMagick website.  The Github index.html is correct.  It's designed to work after you install ImageMagick on your local system.  For example, the page is rendered properly when accessed after an install like this:

```
firefox /usr/local/share/doc/ImageMagick-6/index.html
```

**Comment by mooninite** [comment]
> Got it now. Notice your link in your original posting does not mention Github, but instead points to the ImageMagick website. 
No it doesn't.

> The Github index.html is correct. It's designed to work after you install ImageMagick on your local system. For example, the page is rendered properly when accessed after an install like this:
> 
> ```
> firefox /usr/local/share/doc/ImageMagick-6/index.html
> ```

Doesn't work here. Clicking any of the links with "www/www/<filename>.html" are broken because a "www/www" folder does not exist.

In any case it looks like @Cristy noticed their bad commit and just commited a fix for it a few hours ago. I wish they would have commented here or referenced this issue in their commit.
