### ISSUE TITLE
Debian bug

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick6#90]
Hi,

A new debian bug on your side

Could you get a glimpse ?

https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=966436

BTW can christy could send me a mail (is usual mail adress seems to be burned), need to talk.

Bastien (rouca@debian.org)

**Comment by bastien-roucaries** [comment]
Ping ?

**Comment by urban-warrior** [comment]
Much like scraping a web page, there is some risk as web pages change.  The same here with the identify verbose output.  We never guaranteed it won't change as it is human consumable text.  However, we did address the problem by introducing the JSON image format.  The JSON image format encapsulates all the image attributes but in a machine-consumable manner and it is guaranteed not to change other than the possibility of additional attributes.

**Comment by boutil** [comment]
The issue was not so a problem with a change in the output of `identify -verbose` but 
about the strangeness of the first "subproperties". I am pasting below the piece I am talking about in the Debian bug. I find that `8BIM:1999,2998:#1` is strange for a property name (given that it is the content of the `Clipping path` field. Is it intentional?

```
 Properties:
    8BIM:1999,2998:#1: <?xml version="1.0" encoding="iso-8859-1"?>
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="120">
<g>
<path fill-rule="evenodd" style="fill:#000000;stroke:#000000;stroke-width:0;stroke-antialiasing:false" d="
M 25 44
L 136 44
L 136 97
L 25 97
L 25 44
"/>
</g>
</svg>

    date:create: 2018-03-18T05:54:04+00:00
    date:modify: 2018-03-18T05:54:04+00:00
[...]
```

**Comment by urban-warrior** [comment]
That cryptic line is how you extract a clipping path from a Photoshop profile.   Photoshop stores its paths as resources of type '8BIM' with IDs in the range 2000 through 2998. Check the Adobe Photoshop file format specification for more details.

**Comment by boutil** [comment]
Thank you for the answer. It makes sense. Then this issue can be closed, and I will open one for minimagick ruby gem to fix their regexp.

**Comment by josch** [comment]
>  The JSON image format encapsulates all the image attributes but in a machine-consumable manner and it is guaranteed not to change other than the possibility of additional attributes.

not true: https://github.com/ImageMagick/ImageMagick6/commit/ae0c7c6da22e4faa21dd19b9949c876e26cf8604

I just had switched my codebase from parsing the identify output to parsing json, trusting on the "guaranteed not to change" part and now I have to again support multiple attributes for old and new IM versions...

**Comment by urban-warrior** [comment]
The attributes did not change, its a spelling correction.  Spelling counts for people with OCD.

**Comment by josch** [comment]
I appreciate that the spelling got corrected. But if a supposedly machine readable format changes the name of one of its fields, then it needs to include a version number and that number needs to be bumped so that the machine parsing the json knows whether to expect "endianess" or "endianness". Unfortunately, for a machine, a spelling fix is more than just an "OCD problem" -- just changing a single character will make a file not get interpreted correctly anymore.

**Comment by urban-warrior** [comment]
Understood.  We believe this patch was a user supplied pull that was not vetted properly.  Apologies for that.

**Comment by urban-warrior** [comment]
Forgot to mention, we'll add a patch to add a version #, introduce the old spelling, and provide access to the previous behavior with a define.  We'll need a few days to code up a solution.

**Comment by josch** [comment]
Thank you!! :heart:

**Comment by urban-warrior** [comment]
With the latest patch, specify the JSON model schema version with -define json:version. The current version is 1.0. Any version less than 1.0, returns the original JSON output which includes misspelled labels.

**Comment by josch** [comment]
Excellent! Thank you, @urban-warrior :+1:
