### ISSUE TITLE
endianess undefined in json output

### ISSUE THREAD

**Issue by josch** [ImageMagick/ImageMagick6#91]
Hi,

I'm using imagemagick 8:6.9.11.24+dfsg-1 on Debian unstable. I'm using this TIFF image as input:

https://sources.debian.org/src/img2pdf/0.3.6-1/src/tests/input/mono.tif/

(I cannot attach the image to this issue because github does not allow tif...)

When I check endianness via `identify -verbose | grep -i endian` everything is fine:

```
identify -verbose src/tests/input/mono.tif | grep -i endian
  Endianess: LSB
    tiff:endian: lsb
```

But not so in the json output:

```
convert src/tests/input/mono.tif json: | grep endian
    "endianess": "Undefined",
      "tiff:endian": "lsb",
```

The json value for "endianess" should also be "LSB" and not "Undefined".

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
