### ISSUE TITLE
Imagick broken/spilled  colors 

### ISSUE THREAD

**Issue by pastebimas** [ImageMagick/ImageMagick6#93]
### Description
We have a system that generates .png files by adding some designs on blank canvas. Each file is ~25mb. Suddenly we've started having problems that the files get weird colors and couldn't see a pattern for that. You can retry the same job and the next time it is generated correctly.

Any ideas what might cause that?

Here is the visual: https://gyazo.com/536468054aebe0eb1c296ab29a20e877 https://gyazo.com/0a311dd4345206206dff5d1324082fde

 
### System Configuration

- ImageMagick version: 6.9.7-4
- Environment (Operating system, version and so on): Ubuntu 18
- Additional information:

Server is with the newest AMD processor, 32gb rams and 1TB ssd.

**Comment by dlemstra** [comment]
I would advise you to upgrade to a more recent version? Might be a bug in that older version.

**Comment by Danack** [comment]
@pastebimas

> Any ideas what might cause that?

Reading from uninitialised memory, or very unlikely, bad memory in the computer.

If it's still an issue, maybe post some code that causes it to happen?
