### ISSUE TITLE
Infinite loop Reading an SVG with MSVG

### ISSUE THREAD

**Issue by edman007** [ImageMagick/ImageMagick6#96]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I try to convert some SVGs to PNG (or any other format, like jpg), `convert` enters an infinite loop. Tested on two seperate debian buster systems running ImageMagick 6.9.10-23, I confirmed it on git master (ImageMagick6), my slackware system running 7.0.10-24 does NOT have this problem. The loop appears to be in RenderMVGContent, and best I can tell it's doing a push/pop and then see's a class from the svg and puts the same push/pop back on the stack. I git bisected this and it appears to be f6bf2ee81bf2f25051b3a5176bc4f18358f43243, I have no idea how that causes this
### Steps to Reproduce

I was converting many of the SVGs in KDE breeze-icons to PNGs, this bug happens on many of their SVGs
```bash
git clone https://github.com/KDE/breeze-icons.git
git clone https://github.com/ImageMagick/ImageMagick6.git
cd ImageMagick6
./bisect-script.sh # see below
```
This is my bisect script:
```bash
#!/bin/bash
autoconf
if ! ./configure --disable-deprecated  --with-quantum-depth=16  --with-jemalloc=no  --with-umem=no  --with-autotrace=no  --with-dps=no  --with-fpx=no  --with-gslib=no  --with-fontpath=  --with-gs-font-dir=/usr/share/fonts/type1/gsfonts  --with-gvc=no  --with-rsvg=no ; then
    exit 125
fi
if ! make -j15 ; then
    rm configure
    exit 125
fi    
./utilities/convert -verbose  msvg:../breeze-icons/icons/actions/16/media-playback-start.svg /tmp/start.png &
PID=$!
sleep 15
if kill $PID ; then
    echo bug
    RET=1
else
    echo no bug
    RET=0
fi
make clean
rm configure
exit $RET
```
### System Configuration

- ImageMagick version: 6.9.10-23, git master
- Environment: x86_64 debian buster
- Additional information: See Above

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick within a few days.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ shortly after we commit a patch.

**Comment by edman007** [comment]
I just ran the updated version and tested it against the full breeze-icons set that was giving me trouble, and the patch seems to work. Thank you!
