### ISSUE TITLE
Imagemagick seems to ignore the specified custom temporary path location

### ISSUE THREAD

**Issue by lovasoa** [ImageMagick/ImageMagick6#99]
### Description
When trying to specify a custom location for ImageMagick's pixel cache, it ignore it and keeps using `/tmp`

### Steps to Reproduce
```bash
chmod 777 /home/ophir/tmp/
export MAGICK_TEMPORARY_PATH=/home/ophir/tmp/
export MAGICK_TMPDIR=/home/ophir/tmp/
convert -debug cache -quality 70 -limit memory 8GB -define registry:temporary-path=/home/ophir/tmp/ -define resource:temporary-path=/home/ophir/tmp huge.png huge.jpg
```

### Result 

```
2020-09-13T15:36:26+02:00 0:03.030 1.610u 6.9.10 Cache convert-im6.q16[7392]: cache.c/DestroyPixelCache/1182/Cache
  destroy 
2020-09-13T15:36:26+02:00 0:03.030 1.610u 6.9.10 Cache convert-im6.q16[7392]: cache.c/DestroyPixelCache/1182/Cache
  destroy 
2020-09-13T15:36:26+02:00 0:03.030 1.610u 6.9.10 Cache convert-im6.q16[7392]: cache.c/SetPixelCacheExtent/3825/Cache
  extend /tmp/magick-7392IfTHI09BY1N7[0] (/tmp/magick-7392tOaMobb0ewea[4], disk, 15.3103GB)
...
2020-09-13T15:43:59+02:00 0:05.030 5.560u 6.9.10 Cache convert-im6.q16[8026]: cache.c/WritePixelCachePixels/5979/Cache
  /tmp/magick-8026jdZlabUCCon5[0][40192x1+0+9520]
2020-09-13T15:43:59+02:00 0:05.050 5.610u 6.9.10 Cache convert-im6.q16[8026]: cache.c/DestroyPixelCache/1182/Cache
  destroy /tmp/magick-8026jdZlabUCCon5[0]
convert-im6.q16: unable to write pixel cache `/tmp/magick-80266xWqWMqkN8n5': No space left on device @ error/cache.c/WritePixelCachePixels/5973.
convert-im6.q16: no images defined `huge.jpg' @ error/convert.c/ConvertImageCommand/3258.
``` 

### System Configuration

- ImageMagick version: 6.9.10-23
- Environment (Operating system, version and so on): 
  - `Linux 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Additional information:

**Comment by urban-warrior** [comment]
Check your system-installed security policy, `policy.xml`.  Does it include

```
<policy domain="resource" name="temporary-path" value="/tmp"/>
```
System policies override any local changes.  If you comment out the temporary-path policy in the system-installed `policy.xml` configuration file, you will then be able to change the temporary path with environment variables.

**Comment by urban-warrior** [comment]
List your security policies:
```
convert -list policy
```
If it includes a `temporary-path` policy, it will override any local configurations.  To enable local customizations, you will need comment-out the `temporary-path` policy in your system `policy.xml` configuration file.

**Comment by lovasoa** [comment]
Hello and thank you for your quick answer ! This solved my problem. 

It is a little bit confusing that the tool silently ignores environment variables and command-line parameters, but the most important is that I got it to work :slightly_smiling_face:

**Comment by urban-warrior** [comment]
We could document that fact better, but it makes perfect sense.  If your host administrator sets security policies system-wise, a user should not be able to override the policy.  There is some flexibility in that the user can lower a limit but not raise it past what the system administrator has set.

**Comment by lovasoa** [comment]
Yes, I understand the logic behind that. But it would be easier if the tool explicitly said something like 

> Ignoring argument XXX because it conflicts with setting XXX in file YYY

instead of silently accepting the argument, but not taking it into account.
